### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by CrazyBoyFeng** [kaitoy/pcap4j#1]
At first, thanks for your contribution.
I was used to find serveral java pcap wrapper for a long time, at last, I find the way using JNA is much better. Because it supports the max number of platforms. And it is easy to deploy (no JNI wrapper need), easy to setup and use (only an app.jar and a jna.jar). so pcap4j is really very nice to me.
But I have some problems, wish to give you some help:
1.suggest you to split pcap4j to more functional jars. For example, such as pcap4j.jar for pure wrapper, analyzer4j.jar for analyzing various packet protocol, dump4j.jar for dumping and reading pcap files, other jars for other functions. splitting them to different project functionally make better to use them. sometimes, somebody maybe only want to get an analyzer but dumper. And sometimes oppositely.
2.I find that pcap4j.jar has many useless files, such as examples. When we use pcap4j.jar as a library, how can we use the example in the library? and the role of the pcap files in pcap4j.jar is confusing, either. In addition, I always find some class which have not been called for. If you prepare  to release a jar, I suggest you to make it clean and tiny.
3.I don't think use log in a library is a good idea. you should use state code and exceptions to control the runtime, instead of output log. Log should be used by app or test. So there is a advice to wish you cancel the library output. Leave only jna.jar and pcap4j.jar.
4.Pcap4j is no longer compatible with the newest jna, please update it.
And some questions:
1.Does pcap4j support MacOS?
2.When does pcap4j prepare to support BSD?

**Comment by wumo** [comment]
@kaitoy There're still much annoying log that is not produced by slf4j, when I disable slf4j logging using various methods( nop.jar or logback.xml).  such log just keep records of raw packet, which is very inefficient and annoying. can I totally disable it ?
