### ISSUE TITLE
DnsPacket and 1.7.1 release

### ISSUE THREAD

**Issue by ShunxinLu** [kaitoy/pcap4j#103]
Hello Kaito, please excuse me if this issue has already been addressed. I am planning to use pcap4j for extracting DNS informations from packets, but it seems like this feature is only available in 1.7.1-SNAPSHOT now. So are you planning to do the final 1.7.1 release soon?
Thanks!

**Comment by kaitoy** [comment]
Hello @ShunxinLu.
Yes, it's coming very soon.

**Comment by kaitoy** [comment]
Done.
