### ISSUE TITLE
packet timestamp

### ISSUE THREAD

**Issue by igreenfield** [kaitoy/pcap4j#105]
Hi I am using this API: `pcapHandle.loop(-1, listener, pool);`

When I read the Timestamp I see that it comes out of order. I see HTTP response coming before the request. 

![image](https://user-images.githubusercontent.com/5586356/27024854-fd5f4b64-4f60-11e7-9c5c-376426a8f988.png)

I read the timestamp using:  `pcapHandle.getTimestamp();`

Am I using it wrong? if not how come that the seq and ack are wrong base on the timestamp

**Comment by kaitoy** [comment]
It looks the response is not for the request.
When a server receives a request from a client, it sends back a response with setting the sequenceNumber of the response to the acknowledgementNumber of the request.
But, your request's acknowledgementNumber and your response's sequenceNumber are different, 1750063067 and 1750062851.

**Comment by yersinjacob** [comment]
I have a question, I am working with the packages to make a "packet retarder" and I need to know the exact moment when a package is entering the pc, I have heard that the timestamp could work or else the systemcurrentomilis, which of the two Would I capture that moment?
