### ISSUE TITLE
Less Filter Doesn't Work

### ISSUE THREAD

**Issue by PsiLupan** [kaitoy/pcap4j#106]
The filter I'm using is: "udp && len < 150" to only monitor packets with a size of less than 150 bytes. However, I'm getting packets with sizes upwards of 1200 bytes as reported by the packet.length(). The greater syntax seems to work just fine as far as I can tell.

I'm using the latest Pcap4j 1.7.1 along with Npcap 0.86. Issue was present in the 1.7.1 snapshot builds, though I've not tried with WinPcap to determine if there's a driver issue. I've also tried "udp && !(len >= 150)" among other forms of the "less" syntax.

I don't have any Wireshark captures on hand, but can provide some later if necessary as well as a full code example.

The relevant snippet:
```final int snapLen = 65536;
final PromiscuousMode mode = PromiscuousMode.NONPROMISCUOUS;
final int timeout = 0;
handle = nif.openLive(snapLen, mode, timeout);
handle.setFilter("udp && len < 150)", BpfProgram.BpfCompileMode.OPTIMIZE);

**Comment by kaitoy** [comment]
I couldn't reproduce the problem.
Could you provide a full code?

**Comment by PsiLupan** [comment]
Threw this gist together to demonstrate:

https://gist.github.com/PsiLupan/0ec0d9aa0a9c1e7992c7175ca2ece9f6

`305
305
305
305
305
126
305
305
305
305
305
305
305
305
305
126
305`

This is an example output. With WireShark using "udp && len <= 150," it seems I'm getting the same results though. Which confuses me, because the len of the packet isn't <= 150 bytes.

**Comment by PsiLupan** [comment]
So, did a bit more digging, it looks like it won't except anything with a less below 42 bytes, which is the size of the packet minus the UDP payload.

**Comment by kaitoy** [comment]
Your code have no import and no definition for `snapLen`.
A typo in the first argument of `handle.setFilter`.
Please provide complete code you actually executed.

**Comment by PsiLupan** [comment]
Sorry, was trying to copy it over from my actual code and work on it in a text editor to keep it from being 1000 additional lines.

Regardless, since it affects the Wireshark capture filter, it must be a driver issue. So, I guess I'll close this out.
