### ISSUE TITLE
Get source/destination port from Header

### ISSUE THREAD

**Issue by leonidas183** [kaitoy/pcap4j#109]
Hi, 

I was wondering if it was possible to get the source/destination port from the Header class. I mean, actually, I have:

`Packet packet = requestPackets.take();`

`packet` could be either an IpV4Packet or IpV6Packet and I need to get the source/destination port from the payload header (which could be UPD, TCP, etc.).  But `packet.getPayload().getHeader()` return only a Header object which only has length() and getRawData(). 

Could you add these two methods in the interface Header ?  Or do you have an idea on how to get the src/dst port without knowing the payload class?

**Comment by kaitoy** [comment]
Hi,

Yes, you can. Ports are in TcpPacket or UdpPacket, so to get them you can do like:

```java
packet.get(TcpPacket.class).getHeader().getSrcPort();
```
