### ISSUE TITLE
RadiotapData MAC timestamp does not work on Linux

### ISSUE THREAD

**Issue by lennartkoopmann** [kaitoy/pcap4j#117]
I'm running the following code:

```java
public static Dot11MetaInformation parse(ArrayList<RadiotapPacket.RadiotapData> dataFields) {
    ...

    for (RadiotapPacket.RadiotapData f : dataFields) {
        if(found == 6) {
            break;
        }

        if(f instanceof RadiotapDataAntennaSignal) {
            antennaSignal = ((RadiotapDataAntennaSignal) f).getAntennaSignalAsInt();
            found++;
        } else if (f instanceof RadiotapDataChannel) {
            frequency = ((RadiotapDataChannel) f).getFrequencyAsInt();
            found++;
        } else if (f instanceof RadiotapDataAMpduStatus) {
            delimiterCrcError = ((RadiotapDataAMpduStatus) f).isDelimiterCrcError();
            found++;
        } else if (f instanceof RadiotapDataRxFlags) {
            badPlcpCrc = ((RadiotapDataRxFlags) f).isBadPlcpCrc();
            found++;
        } else if (f instanceof RadiotapDataFlags) {
            badFcs = ((RadiotapDataFlags) f).isBadFcs();
            isWep = ((RadiotapDataFlags) f).isWepEncrypted();
            found++;
        } else if (f instanceof RadiotapDataTsft) {
            macTimestamp = ((RadiotapDataTsft) f).getMacTimestamp().longValue();
            found++;
        }
    }

    ...
```

The MAC timestamp (`((RadiotapDataTsft) f).getMacTimestamp().longValue()`) is successfully parsed on OSX but not on Linux.

Linux:

```
Pcap4J successfully loaded a native pcap library: libpcap version 1.8.1
```

OSX:

```
Pcap4J successfully loaded a native pcap library: libpcap version 1.8.1 -- Apple version 67.50.2
```

PCAP4j: v1.7.1

The OSX WiFi adapter is the onboard one of a MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) and an ALFA AWUS051NH v2.

Everything else works perfectly well and any help is appreciated.

**Comment by kaitoy** [comment]
What happened on Linux?
What did you expect and what's the difference from the expectation?

**Comment by lennartkoopmann** [comment]
Thanks for the reply! Sorry for not being more specific.

On Linux, `((RadiotapDataTsft) f).getMacTimestamp().longValue()` returns `null` and I expected it to return the timestamp like on OSX.

**Comment by kaitoy** [comment]
Could you provide me the packet on Linux?

**Comment by kaitoy** [comment]
If possible I want to see the result of `System.out.println(ByteArrays.toHexString(packet.getRawData(), ""));`

**Comment by lennartkoopmann** [comment]
Sorry for being late on this. I double checked with Wireshark and it looks like the driver of my WiFi adapter is simply not setting the MAC timestamp field. I assume that it will work with drivers that set this field.

Thank you again!
