### ISSUE TITLE
Open pcap from byte array?

### ISSUE THREAD

**Issue by camsteffen** [kaitoy/pcap4j#120]
Is there an equivalent to `Pcaps.openOffline` for opening a pcap file in memory as a byte array?

**Comment by kaitoy** [comment]
Could you write a pseudo code that explains what you want do?

**Comment by camsteffen** [comment]
Here is how I imagine it.
```java
byte[] data = readPcapFromDB();
PcapHandle handle = Pcaps.openOffline(data);
Packet packet = getNextPacket();
handle.close();
```
or perhaps there is a way to access stdin? The docs for [`Pcaps.openOffline`](http://static.javadoc.io/org.pcap4j/pcap4j/1.7.1/org/pcap4j/core/Pcaps.html#openOffline(java.lang.String)) say "-" means stdin.

```java
byte[] data = readPcapFromDB();
PcapHandle handle = Pcaps.openOffline("-");
OutputStream stdin = handle.getOutputStream();
stdin.write(data);
Packet packet = getNextPacket();
handle.close()
```
`PcapHandle.getOutputStream` here would be similar to [`Process.getOutputStream`](https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#getOutputStream--)

**Comment by kaitoy** [comment]
There is no API for such a purpose for now.
Pcap4J is a wrapper of libpcap and libpcap doesn't have API to read packets from pcap data in memory.
Pcap4J neither implements its own API to parse pcap data.

If there is a way to connect an output stream to the stdin of the JVM process that runs Pcap4J, maybe `Pcaps.openOffline("-")` works.
If not, you need to write the data to a file before Pcap4J can read it.

**Comment by SahilGuptaQVT** [comment]
Hi , 

> There is no API for such a purpose for now.
> Pcap4J is a wrapper of libpcap and libpcap doesn't have API to read packets from pcap data in memory.
> Pcap4J neither implements its own API to parse pcap data.
> 
> If there is a way to connect an output stream to the stdin of the JVM process that runs Pcap4J, maybe `Pcaps.openOffline("-")` works.
> If not, you need to write the data to a file before Pcap4J can read it.

Hi , 
What type of file do we need to create from byte[] ?
And how can we parse that file to get sample.pcap (PCAP file) ?

for example : I am able to make text file with hex data from byte[]. and parse that file using text2pcap to make .pcap file. Can I do something similar here ?

**Comment by kaitoy** [comment]
Pcap4J can read PCAP files on file system.
I don't know how to create such files from byte[].
