### ISSUE TITLE
Add support for immediate mode

### ISSUE THREAD

**Issue by racorn** [kaitoy/pcap4j#128]
Add support for setting immediate mode,
http://www.tcpdump.org/manpages/pcap_set_immediate_mode.3pcap.html.

See pull request #127 

Immediate mode will allow programs to process packets as soon as they
arrive. This may reduce latency when writing a request/response type application, for example answering ICMP echo requests (ping).

Immediate mode is supported from version 1.5.0 of libpcap, see this thread for more information:

http://seclists.org/tcpdump/2014/q4/57

With the code snippet below, I could get ping responses of about 200 microseconds, which was not possible without immediate mode. Note that while the timeout does not apply to how quickly the listener gets the captured packages, it applies when you want to break the loop.

```java
PcapNetworkInterface nif = Pcaps.getDevByAddress(...);

PcapHandle inboundHandle = new PcapHandle.Builder(nif.getName())
                .promiscuousMode(PromiscuousMode.PROMISCUOUS)
                .direction(PcapDirection.IN)
                .timeoutMillis(100)
                .immediateMode(true)
                .snaplen(16_384).build();
...

inboundHandle.loop(-1, new PingListener());
```

**Comment by kaitoy** [comment]
#127 was merged.
