### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-x86-64/libjnidispatch.so) not found in resource path (.)

### ISSUE THREAD

**Issue by Pakyto** [kaitoy/pcap4j#129]
Hi, i'm develop android app for sniffing packets from device.
I'm using pcap4j library, but when call Pcaps.getDevByAddress(), launches the exception.
Can you help me?
                `InetAddress destAddr = parsedPacket;
                PcapNetworkInterface nif = Pcaps.getDevByAddress(destAddr);`

Thanks

**Comment by kaitoy** [comment]
Sorry, but I can't.
Pcap4J now doesn't support Android officially and I'm not familiar with it neither.
There seems some users using Pcap4J on Android. Please post your question with the detail of the exception and the device in StackOverflow and see if they can answer it.
