### ISSUE TITLE
MacOSX malloc exception

### ISSUE THREAD

**Issue by subnetmarco** [kaitoy/pcap4j#13]
I'm trying to run the [GetNextPacket](https://github.com/kaitoy/pcap4j/blob/master/pcap4j-sample/src/main/java/org/pcap4j/sample/GetNextPacket.java) sample on MacOSX 10.9.2 and I'm getting the following exception after successfully intercepting some packets:

```
java(2395,0x10fde9000) malloc: *** error for object 0x7fa634a02208: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

**Comment by lennartkoopmann** [comment]
Thank you! I can confirm that switching to `GetNextPacketEx` fixed this issue for me on OSX.

**Comment by kaaquist** [comment]
@lennartkoopmann : Can you spare some more insight on what you did.. I'm seeing this error too using Pcap4j w. Scala on Mac 10.12.5. Scala 2.12.1 and SBT 0.13.15. 
Error: 
```
java(23455,0x700006e90000) malloc: *** error for object 0x7f8abfcd7898: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

Was enough for you to just change to `GetNextPacketEx` or did you `brew install` some specific version of `libpcap`? Thanks.

**Comment by lennartkoopmann** [comment]
@kaaquist All I did was switching to `GetNextPacketEx` and that fixed it. OSX 10.12.4
