### ISSUE TITLE
Cannot Defragment Packet

### ISSUE THREAD

**Issue by zzenonn** [kaitoy/pcap4j#131]
Hello, @kaitoy,

Thank you for answering my [question](https://github.com/kaitoy/pcap4j/issues/126) on the fragmented packet, however, whenI try to parse the [packet file](https://github.com/kaitoy/pcap4j/files/1400670/splits.pcap.zip) using the `IpV4Helper.defragment(list)` method, it says I cannot defragment the packet. I checked the packets on Wireshark and found that those were the only two fragmented packets with the same identification.

This is the error messaged I received:
> Exception in thread "main" java.lang.IllegalArgumentException: Can't defragment: [[IPv4 Header (20 bytes)]
>   Version: 4 (IPv4)
>   IHL: 5 (20 [bytes])
>   TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
>   Total length: 1500 [bytes]
>   Identification: 46655
>   Flags: (Reserved, Don't Fragment, More Fragment) = (false, false, true)
>   Fragment offset: 0 (0 [bytes])
>   TTL: 55
>   Protocol: 17 (UDP)
>   Header checksum: 0x7f55
>   Source address: /109.97.67.71
>   Destination address: /92.27.27.185
> [Fragmented data (8 bytes)]
>   Hex stream: 8f 8c 1f 90 05 ed 6b b0
> , [IPv4 Header (20 bytes)]
>   Version: 4 (IPv4)
>   IHL: 5 (20 [bytes])
>   TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
>   Total length: 57 [bytes]
>   Identification: 46655
>   Flags: (Reserved, Don't Fragment, More Fragment) = (false, false, false)
>   Fragment offset: 185 (1480 [bytes])
>   TTL: 55
>   Protocol: 17 (UDP)
>   Header checksum: 0xa43f
>   Source address: /109.97.67.71
>   Destination address: /92.27.27.185
> ]

Thanks!

**Comment by kaitoy** [comment]
It's because your packets were not completely captured (i.e. were [truncated](https://osqa-ask.wireshark.org/questions/50808/packet-size-limited-during-capture-xxxxxx-truncated)). You need to adjust capturing parameters so you can defragment packets correctly.
