### ISSUE TITLE
[Question] Redirecting packets

### ISSUE THREAD

**Issue by rp25** [kaitoy/pcap4j#132]
Is it possible to capture and redirect packets using this library at a rate of ~700 PPS forever?

**Comment by kaitoy** [comment]
Sorry, but I have no idea.
I've never tested Pcap4J in terms of performance, actually.

**Comment by rp25** [comment]
`import java.io.IOException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.pcap4j.core.NotOpenException;
import org.pcap4j.core.PacketListener;
import org.pcap4j.core.PcapHandle;
import org.pcap4j.core.PcapNativeException;
import org.pcap4j.core.PcapNetworkInterface;
import org.pcap4j.core.PcapNetworkInterface.PromiscuousMode;
import org.pcap4j.packet.Packet;
import org.pcap4j.util.NifSelector;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;

public class HeavyLoop {

  public static void main(String[] args) throws PcapNativeException, NotOpenException {
    PcapNetworkInterface nif;
    try {
      nif = new NifSelector().selectNetworkInterface();
    } catch (IOException e) {
      e.printStackTrace();
      return;
    }

    if (nif == null) {
      return;
    }

    System.out.println(nif.getName() + "(" + nif.getDescription() + ")");
    final PcapHandle handle = nif.openLive(65536, PromiscuousMode.PROMISCUOUS, 10);       
    PacketListener listener = new PacketListener()
    {
          @Override
          public void gotPacket(Packet packet) 
          {        	  
        	DatagramSocket socket = null;  
        	try {
				socket = new DatagramSocket(4445);
			} catch (SocketException e1) 
        	{
				e1.printStackTrace();
			}
        	DatagramPacket sendpacket; 
        	InetAddress adder = null;
			try {
				adder = InetAddress.getByName(ip); // (String) ip
			} catch (UnknownHostException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        	sendpacket = new DatagramPacket(packet.getRawData(), packet.length(), adder, port); //(int) port
        	try {
				socket.send(sendpacket);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        	socket.close();

          }
	};

    try {
      ExecutorService pool = Executors.newFixedThreadPool(4);
      handle.loop(-1, listener, pool); 
      
      pool.shutdown();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    handle.close();
  }
  
  private HeavyLoop() {}

}`

I modified heavyloop to capture and resend packets to another address. I'm having an issue where i'm sending ~1000 time more packets them I am receiving. Thoughts?
