### ISSUE TITLE
Cooked mode with wirless interface

### ISSUE THREAD

**Issue by saya7** [kaitoy/pcap4j#133]
Hi,
i get this error when i am trying to send udp packet throw wireless interface
org.pcap4j.core.PcapNativeException: Error occured in pcap_sendpacket(): Sending packets isn't supported in cooked mode

**Comment by kaitoy** [comment]
It means the pcap native library Pcap4J wraps doesn't support sending cooked packets on the interface.
There is no way to address the error from Pcap4J side.
You need to send the packets in another way.
