### ISSUE TITLE
Null timestamps

### ISSUE THREAD

**Issue by abossert** [kaitoy/pcap4j#134]
I am using Pcap4j 1.7.2 within an Apache Storm topology and am seeing packets that get pulled from a PCAP file that do not seem to return a valid timestamp from the PcapHandle.  Below is the code for the Storm Bolt that is grabbing the packets and timestamps.  Also, when I implement my own loop (e.g. while loop logic with getNextPacketEx does not return EOF error), I am able to handle packet errors naturally using try/catch/finally blocks, but in the loop method, I only have the ability to implement the gotPacket method, which leaves me no way to catch bad packets.  These two issues have cause a great deal of head scratching and I am not sure where to go with this.  FInally, It would make much more sense to have the timestamp for each individual packet as a part of the Packet object/Class...It does not seem to make sense to have to get it from the Handle.

```scala
package org.anonymous.apachestormstreaming.storm.bolts.microbatch

import java.io.File
import java.time.Instant
import java.util
import java.util.concurrent.{ExecutorService, Executors}
import scala.collection.mutable.ListBuffer
import org.apache.storm.task.{OutputCollector, TopologyContext}
import org.apache.storm.topology.OutputFieldsDeclarer
import org.apache.storm.topology.base.BaseRichBolt
import org.apache.storm.tuple.{Fields, Tuple, Values}
import org.pcap4j.core.PcapHandle.TimestampPrecision
import org.pcap4j.core.{PacketListener, PcapHandle, Pcaps}
import org.pcap4j.packet.Packet
import org.pcap4j.packet.namednumber.DataLinkType
import org.slf4j.{Logger, LoggerFactory}

class PcapReaderBolt extends BaseRichBolt {
    var context: TopologyContext = _
    var conf: util.Map[_, _] = _
    var collector: OutputCollector = _
    val logger: Logger = LoggerFactory.getLogger(classOf[PcapReaderBolt])
    var batchSize: java.lang.Long = _
    var timestamp: Instant = _
    
    override def prepare(stormConf: util.Map[_, _], stormContext: TopologyContext, stormCollector: OutputCollector): Unit = {
        context = stormContext
        conf = stormConf
        collector = stormCollector
        batchSize = conf.get("org.anonymous.configuration.PcapReaderBolt.batchsize").asInstanceOf[java.lang.Long]
    }
    
    override def declareOutputFields(declarer: OutputFieldsDeclarer): Unit = {
        declarer.declareStream("packets",new Fields("batch"))
    }
    
    override def execute(input: Tuple): Unit = {
        val file_rowkey: String = input.getStringByField("file_rowkey")
        val filename: String = input.getStringByField("file")
        val fileObj: File = new File(filename)
        val pcapFileHandle: PcapHandle = Pcaps.openOffline(fileObj.getAbsolutePath)
        val dlt: DataLinkType = pcapFileHandle.getDlt
        val precision: TimestampPrecision = pcapFileHandle.getTimestampPrecision
        val batch: ListBuffer[Values] = new ListBuffer[Values]()
        
        try {
            val listener: PacketListener = (packet: Packet) => {
                timestamp = pcapFileHandle.getTimestamp.toInstant
                batch += new Values(packet,file_rowkey,dlt,precision,timestamp)
    
                if (batch.length > batchSize.toInt) {
                    collector.emit("packets", input, new Values(batch))
                    batch.clear()
                }
            }
            val pool: ExecutorService = Executors.newFixedThreadPool(16)
            pcapFileHandle.loop(-1,listener,pool)
            pool.shutdown()
            pcapFileHandle.close()
        } catch {
            case e: InterruptedException =>
                logger.error("LOOP WAS MANUALLY INTERRUPTED: " + e.getMessage + "\n" + e.getStackTrace.mkString("\n"))
                collector.fail(input)
            case e: Exception =>
                logger.error(e.getMessage + "\n" + e.getStackTrace.mkString("\n"))
                collector.fail(input)
        } finally {
            if(batch.nonEmpty) {
                collector.emit("packets",input,new Values(batch))
            }
            collector.ack(input)
        }
    }
}
```

**Comment by kaitoy** [comment]
In Pcap4J v2, which is now under development, a timestamp will comes with a packet object, so you will be able to handle it more easily.

**Comment by abossert** [comment]
That is great to hear, but unfortunately is a problem without knowing the release date of V2.  Any idea of when that might be?  I know I asked that before, but now I have a fairly serious issue to deal with related to the null timestamps.

**Comment by kaitoy** [comment]
I aim to release v2 beta in this year. The timestamp improvement will come with the beta.

**Comment by abossert** [comment]
Perfect.  By the way I have been working on a fairly robust TCP session class.  Once I get the code mostly done, I’m happy to share it if you are interested.  The class handles/tracks packet loss and midstream/incomplete collection.

--
M. Aaron Bossert
PUNCH Cyber Analytics Group
aaron@punchcyber.com<mailto:aaron@punchcyber.com>
(571) 242-4021
www.PUNCHcyber.com<http://www.punchcyber.com/>

[/Users/mbossert/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_867219942]

**Comment by kaitoy** [comment]
Thank you. I'm interested in it.
I would like to see it.
