### ISSUE TITLE
TCP Reassembly

### ISSUE THREAD

**Issue by abossert** [kaitoy/pcap4j#135]
I saw in the project tasks for V2 that you are going to implement TCP reassembly.  I need this feature and was hoping to avoid reinventing the wheel.  Is it possible to either provide me with the source for the reassembler or to patch 1.7.2 with that code assuming it is already complete?

**Comment by kaitoy** [comment]
No, it's actually not yet implemented. 
But [here](https://gist.github.com/kaitoy/2aca1d6b8644fcccf0cfa5d30f5fe573) is my basic idea for that.
