### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: nanos > 999999999 or < 0

### ISSUE THREAD

**Issue by hoseiney** [kaitoy/pcap4j#137]
I want use openOffline method and when I try getNextRawPacketEx for each packet,
this error  appeared:
 Exception in thread "main" java.lang.IllegalArgumentException: nanos > 999999999 or < 0 

part of my Pcap file in Wireshark :
![image](https://user-images.githubusercontent.com/24523821/33237990-4ae4fe28-d298-11e7-843f-d19874747bfd.png)

**Comment by kaitoy** [comment]
I guess it's because of precision mismatch.
Please try `Pcaps#openOffline(String, TimestampPrecision)` with different precisions.

**Comment by kaitoy** [comment]
Have you solve the problem?
