### ISSUE TITLE
VMWare issue

### ISSUE THREAD

**Issue by paulkeogh** [kaitoy/pcap4j#138]
I have an application that uses PCAP4J to listen for SCTP packets. It works fine on a native Linux server but when I deploy exactly the same software in a VMWare instance, I only see inbound packets.

Wireshark on the same VMWare instance sees both inbound and outbound packets.

Any ideas on how to approach this problem ?

**Comment by kaitoy** [comment]
It's weird. I often use Pcap4J on a VM of VMware Player,  but I've never seen such a problem.
Could you tell me your environment in detail?

**Comment by kaitoy** [comment]
Are you still seeing the issue?
