### ISSUE TITLE
Can't do the build, MojoFailureException

### ISSUE THREAD

**Issue by Nargarnd** [kaitoy/pcap4j#140]
I'm trying to use pcap4j in my java project, I follow all the steps in the How to build section but when I try to do the mvnw install command I get this error:

Tests run: 69, Failures: 0, Errors: 25, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Pcap4J ............................................. SUCCESS [  0.312 s]
[INFO] Pcap4J Core ........................................ FAILURE [ 13.301 s]
[INFO] Pcap4J Packet Test ................................. SKIPPED
[INFO] Pcap4J Static Packet Factory ....................... SKIPPED
[INFO] Pcap4J Properties-Based Packet Factory ............. SKIPPED
[INFO] Pcap4J Sample ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.784 s
[INFO] Finished at: 2017-12-19T13:15:59+01:00
[INFO] Final Memory: 18M/61M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
15:test (default-test) on project pcap4j-core: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\jmherrerias\pcap4j-1\pcap4j-core\target\surefir
e-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :pcap4j-core

**Comment by kaitoy** [comment]
Have you installed WinPcap or Npcap?
Could you paste all of the error messages?

**Comment by Nargarnd** [comment]
Thanks for the quick answer, I've attached a some txts, with the console output of the error and the versions of all the programs in the dependencies. I've followed the How to build section step by step so I really don't know what could be the problem.

I've also checked the surefire-reports files, only one of the tests has errors, org.pcap4j.Pcap4jPropertiesLoaderTest, the file is attached with the rest.

ErrorLog:
[ErrorOutput.txt](https://github.com/kaitoy/pcap4j/files/1587314/ErrorOutput.txt)

ErrorLog with full debug logging active:
[FullErrorOutput.txt](https://github.com/kaitoy/pcap4j/files/1587326/FullErrorOutput.txt)

org.pcap4j.Pcap4jPropertiesLoaderTest:
[org.pcap4j.Pcap4jPropertiesLoaderTest.txt](https://github.com/kaitoy/pcap4j/files/1587328/org.pcap4j.Pcap4jPropertiesLoaderTest.txt)

MavenVersion:
[MavenVersion.txt](https://github.com/kaitoy/pcap4j/files/1587317/MavenVersion.txt)

WinPcacpVersion:
![winpcapversion](https://user-images.githubusercontent.com/34681197/34356869-14234b80-ea42-11e7-95c5-ffb18b9e2a93.png)

**Comment by kaitoy** [comment]
Java 9 is suspicious. Could you try Java 8?

**Comment by Nargarnd** [comment]
That was it! Problem solved, thank you so much Kaitoy

**Comment by kaitoy** [comment]
I will investigate the Java 9 issue.
