### ISSUE TITLE
Adding support for a protocol with two formats

### ISSUE THREAD

**Issue by Nargarnd** [kaitoy/pcap4j#142]
I'm adding support for a certain protocol, which works with two different formats over the same tcp port, how can I add them to the packet-factory.properties?

I've been looking at these:
[https://github.com/kaitoy/pcap4j/blob/v1/www/HowToAddProtocolSupport.md](url)
[https://www.kaitoy.xyz/2015/08/09/step-by-step-to-add-a-protocol-support-to-pcap4j-1/](url)
[https://www.kaitoy.xyz/2015/10/12/step-by-step-to-add-a-protocol-support-to-pcap4j-2/](url)

But in the example DHCP has only one packet format,so I don't know how to solve the problem.

**Comment by kaitoy** [comment]
Sorry for late response.
[IpSelector class](https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-core/src/main/java/org/pcap4j/packet/IpSelector.java) should be a good sample for you.
