### ISSUE TITLE
An error when I used on MAC os,"pointer being freed was not allocated"

### ISSUE THREAD

**Issue by MrZhouFor** [kaitoy/pcap4j#143]
hi，Thank you for your library.

version: 1.7.3

error: 
`java(775,0x70000d359000) malloc: *** error for object 0x10b2e1ba2: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug`

os:
`macOS High Sierra version:10.13.1`

I made a preliminary judgment that it was wrong here,“Packet packet = handle.getNextPacket();” 
This error occurs when I access a normal Http site, www.java.com ,for example.
The following code copy from the sample class of  org.pcap4j.sample.DumpLoop.

code

		String filter = "host www.java.com";
		PcapNetworkInterface nif;
		try {
			nif = new NifSelector().selectNetworkInterface();
		} catch (IOException e) {
			e.printStackTrace();
			return;
		}
		
		if (nif == null) {
			return;
		}
		PcapHandle.Builder phb = new PcapHandle.Builder(nif.getName())
				.snaplen(SNAPLEN)
				.promiscuousMode(PcapNetworkInterface.PromiscuousMode.PROMISCUOUS)
				.timeoutMillis(READ_TIMEOUT);
		if (TIMESTAMP_PRECISION_NANO) {
			phb.timestampPrecision(PcapHandle.TimestampPrecision.NANO);
		}
		PcapHandle handle = phb.build();

		handle.setFilter(
				filter, BpfProgram.BpfCompileMode.OPTIMIZE
		);

		int        num    = 0;
		PcapDumper dumper = handle.dumpOpen(PCAP_FILE);
		while (true) {
			Packet packet = handle.getNextPacket();
			if (packet != null) {
				System.out.println("packet->" + packet);
				dumper.dump(packet, handle.getTimestamp());
				num++;
				if (num >= COUNT) {
					break;
				}
			}
		}

		dumper.close();
		handle.close();

**Comment by kaitoy** [comment]
Thank you for reporting the error.
Can I see the entire error log?

**Comment by MrZhouFor** [comment]
The Java version I used was 1.8.0_91.
This is the full error log, and nothing else ：
java(1680,0x700002653000) malloc: *** error for object 0x7fc316bf9800: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by MrZhouFor** [comment]
I don't have any problem with the other way：


		
		final PcapHandle handle
				= nif.openLive(SNAPLEN, PcapNetworkInterface.PromiscuousMode.PROMISCUOUS, READ_TIMEOUT);

		handle.setFilter(
				filter,
				BpfProgram.BpfCompileMode.OPTIMIZE
		);

		PcapDumper dumper = handle.dumpOpen(PCAP_FILE);
		try {
			handle.loop(COUNT, dumper);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

**Comment by kaitoy** [comment]
Don't you have JVM crash log like hs_err_pid2075.log ?

**Comment by kaitoy** [comment]
I'm closing this because this ticket is inactive for a long time.
