### ISSUE TITLE
how to get http packet?

### ISSUE THREAD

**Issue by ansguocheng** [kaitoy/pcap4j#147]
how to get the http content,such as user agent?

**Comment by moisedavid** [comment]
Apologies for interjecting, but I believe you need to be able to reassemble TCP packets as they come in. To my knowledge, @kaitoy is working on it for Pcap4J v2, so you can either wait for that release, or try to implement it on your own. Hope this helps answer your question.

**Comment by ansguocheng** [comment]
Now I find that jnetpcap can do it
