### ISSUE TITLE
No packet matches when using bpf-filter

### ISSUE THREAD

**Issue by Nedro** [kaitoy/pcap4j#148]
Hello,

I have encountered a problem while using pcap4j to read from a pcap file.
My code works fine when reading from the file without a filter. But as soon as I set a filter on the pcap handle no packages at all are matched. Even when using a very simple filter that matches packages in the pcap file for sure. I verified it with wireshark.

Here is what my code bascially does:

```
//imports...
//try catches excluded for simplicity

private PcapHandle pcapHandle;
private String filter = "host 13.144.24.198";
private String pcapFile = "SomeFile.pcap";

pcapHandle = Pcaps.openOffline(pcapFile);
BpfProgram bpfFilter = pcapHandle.compileFilter(filter, BpfProgram.BpfCompileMode.OPTIMIZE, PcapHandle.PCAP_NETMASK_UNKNOWN);
pcapHandle.setFilter(bpfFilter);

byte[] rawPacket = null;
while(true) {
  rawPacket = pcapHandle.getNextRawPacket();
  if(rawPacket != null) {
    //do something with rawPacket...
  } else {
    break;
  }
}
```
This code works without setting a bpf filter. It reads every packet from the pcap file as expected.
But as soon as I set a filter, no matter what the filter contains, I don't match any packages.

Do you have any idea or tips on what I am doing wrong?

Thanks and Greetings
Nedro

**Comment by Nedro** [comment]
Update: I played around with it some more and noticed something. If I set the filter expression to "vlan" I can match almost all packages. Am I not able to use higher protocol levels for my filter expression like the tcp src/dest ip?

**Comment by Nedro** [comment]
The problem was that the bpf package filter needs a vlan at the start to "switch modes". Otherwise it can't match any vlan packages. Can be closed.

**Comment by kaitoy** [comment]
Adding "vlan &&" at the beginning like "vlan && host 13.144.24.198" probably works.
It seems you found a solution yourself, though
