### ISSUE TITLE
pcap4j as an OSGI bundle

### ISSUE THREAD

**Issue by maacarbo** [kaitoy/pcap4j#152]
Would it be possible to make bundles out of the jar files, so it can be directly used inside an OSGI container?

**Comment by kaitoy** [comment]
I'm not familiar with OSGi. What would be needed for it?

**Comment by BurakDmb** [comment]
If you are using eclipse plug in development environment, you can simply create a bundle including jar files using gui. 
New project -> Plug-in Development -> Plug-in from Existing JAR Archives -> Select the jar files -> Enter project name and select target platform as an OSGi Framework 

This will create a simple project including these jars and creates a MANIFEST.mf file, heres an example for creating pcap4j bundle including the dependencies. 

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Pcap4j
Bundle-SymbolicName: pcap4j
Bundle-Version: 1.0.0
Bundle-ClassPath: jna-4.2.1.jar,
  pcap4j-core-1.7.3.jar,
  pcap4j-packetfactory-static-1.7.3.jar,
  slf4j-api-1.7.12.jar,
  slf4j-simple-1.6.2.jar
Export-Package: com.sun.jna,
 com.sun.jna.ptr,
 com.sun.jna.win32,
 org.pcap4j,
 org.pcap4j.core,
 org.pcap4j.packet,
 org.pcap4j.packet.constant,
 org.pcap4j.packet.factory,
 org.pcap4j.packet.namednumber,
 org.pcap4j.util,
 org.slf4j,
 org.slf4j.helpers,
 org.slf4j.impl,
 org.slf4j.spi
Bundle-RequiredExecutionEnvironment: JavaSE-1.8 
```

After that you can export this project to create a bundle, follow these steps:
Export -> Plug-in Development -> Deployable plug-ins and fragments -> Select the project that you want to create a bundle -> Adjust the destination directory -> Click finish

**Comment by kaitoy** [comment]
@BurakDmb Thanks a lot!
