### ISSUE TITLE
Not able to parse DNS Answer list properly

### ISSUE THREAD

**Issue by nildeka** [kaitoy/pcap4j#155]
Hi,
    I am unable to parse DNS response accurately using pcap4j libraray version 1.7.3 in Android. I created DnsPAcket from raw bytes. Where I can parse the question list correctly, but answer list has issues. The host name from Answer is always empty.

 ```
DnsPacket dnsPacket = DnsPacket.newPacket(dnsData, 0, dnsData.length);
if( 0 < dnsPacket.getHeader().getAnCount()) {
           List<DnsResourceRecord>answerList = dnsPacket.getHeader().getAnswers();

           for (DnsResourceRecord answer: answerList) {
                     try {
                           if (null != answer.getName()) {
                                  if (answer.getDataType().equals(DnsResourceRecordType.A)) {
                                         String name = answer.getName().getName();
                                         DnsResourceRecord.DnsRData rData = answer.getRData();
                                         String ipaddress = rData.toString();
                                         boolean isIPv4 = ipaddress.split("ADDRESS:")[1].indexOf(':') < 0;
                                         if (isIPv4) {
                                              Log.i(TAG, name+" Address" + ipaddress.split("ADDRESS:")[1]);
                                          }
                                      }
                                 }
                        } catch (Exception e) {
                                    e.printStackTrace();
                         }
                   }
           }
}
```

  Could you please help me resolving it, and how can I retrieve the host name.

Thanks,
Nilanjana

**Comment by kaitoy** [comment]
You mean `answer.getRData()` returns null?
Can I see the packet?

**Comment by nildeka** [comment]
Thanks for the reply. I am getting data for answer.getRData(). But answer.getName().getName() is empty.

Here is my DNS Packet's byte array:

`[-37, -98, -127, -128, 0, 1, 0, 1, 0, 0, 0, 0, 8, 102, 97, 99, 101, 98, 111, 111, 107, 3, 99, 111, 109, 0, 0, 1, 0, 1, -64, 12, 0, 1, 0, 1, 0, 0, 0, 0, 0, 4, -99, -16, 1, 35] `

Thanks.

**Comment by kaitoy** [comment]
It's because `answer.getName().getName()` is actually empty.
`answer.getName()` has a pointer instead. (Please refer to https://tools.ietf.org/html/rfc1035#section-4.1.4)

In this case, you can get name by `answer.getName().decompress(dnsPacket.getHeader().getRawData())`.
