### ISSUE TITLE
Log output in v2

### ISSUE THREAD

**Issue by kylekyle** [kaitoy/pcap4j#156]
Running a pcap4j v2 program prints a number to standard out for every interface found:

```
21:57:07.238 [AWT-EventQueue-0] INFO  org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: libpcap version 1.8.1 -- Apple version 79.20.1
21:57:07.280 [AWT-EventQueue-0] INFO  org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet, use default value: 2
21:57:07.281 [AWT-EventQueue-0] INFO  org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet6, use default value: 30
21:57:07.281 [AWT-EventQueue-0] INFO  org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.packet, use default value: 17
21:57:07.281 [AWT-EventQueue-0] INFO  org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.link, use default value: 18
6
6
6
6
6
6
6
7
0
0
0
0
0
21:57:07.304 [AWT-EventQueue-0] INFO  org.pcap4j.core.Pcaps - 13 NIF(s) found.
```

Not sure what the numbers correspond to. On Windows they are all zero. It's probably just a debug print that got committed, but I couldn't track it down.

**Comment by kaitoy** [comment]
Yes, it's debug print.
It's already removed from master.

**Comment by fordc5** [comment]
Can't find in master but still printing for me

**Comment by kaitoy** [comment]
b4295df is the commit that fixed it.
It's not included in any releases, though.

**Comment by kaitoy** [comment]
Finally, Pcap4J 1.7.4 and 2.0.0-alpha.1 were released with the fix...

**Comment by AlexanderFilip** [comment]
I have a general question, how much is pcap4j the same with jpcap? I just need for a project for capturing packets and types (ipv4,6 tcp udp, etc. ) and showing them. Is Pcap4j suitable for this as I was told told to use Jpcap ?  Thank you
