### ISSUE TITLE
Pcaps.getDevByName not thread-safe

### ISSUE THREAD

**Issue by kylekyle** [kaitoy/pcap4j#157]
I've only see the behavior on Windows (10) under WinPcap (haven't tested on npcap), but when `Pcaps.getDevByName` is called in two separate threads, one returns `null`. Synchronizing the calls fixed it for me. Not really sure if this is actually an issue and it is certainly an edge case.

**Comment by kaitoy** [comment]
`Pcaps.getDevByName` calls a native function. It's not thread-safe, I guess.
I will document it.
