### ISSUE TITLE
2.0.0-alpha can't find NIF，but 1.7.3 is normal

### ISSUE THREAD

**Issue by ansguocheng** [kaitoy/pcap4j#158]
compile group: 'org.pcap4j', name: 'pcap4j-core', version: '2.0.0-alpha'
winpcap4.1.3

[main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.93, based on libpcap version 1.8.1
[main] INFO org.pcap4j.core.Pcaps - No NIF was found.
java.io.IOException: No NIF to capture.
	at org.pcap4j.util.NifSelector.selectNetworkInterface(NifSelector.java:44)

**Comment by kaitoy** [comment]
It's weird. There is no diff around the code that find NIFs between 2.x and 1.x.
Could you explain what you did in detail?

**Comment by kaitoy** [comment]
I'm closing this because this ticket is inactive for a long time.
