### ISSUE TITLE
java.io.IOException: No NIF to capture.

### ISSUE THREAD

**Issue by SyCode7** [kaitoy/pcap4j#159]
Hi, I am trying to use your library but i get the response `java.io.IOException: No NIF to capture.`
What would this mean and is there a way to overcome this error ?? Thanks.

**Comment by SyCode7** [comment]
Okay, I had to reinstall winpcap, the install installation via `choco` was buggy. But now another issue arises as I test some code in Eclipse. Ihae the error below  -- 
`14:53:24.029 [main] INFO  org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.dlt.raw, use default value: 12
Link type: [1 (Ethernet)] handle: [native@0x31a7c80] Open: [true] Filtering Expression: []`

**Comment by kaitoy** [comment]
The message you put is not an error. Just ignore it.
