### ISSUE TITLE
getAcknowledementNumber() != getAcknowledgementNumberAsLong()

### ISSUE THREAD

**Issue by crittje** [kaitoy/pcap4j#161]
Hello,

When I do the following: 

    System.out.println(packet);
    System.out.println("getAcknowledgementNumber " + packet.get(TcpPacket.class).getHeader().getAcknowledgmentNumber());
    System.out.println("getAcknowledgementNumberAsLong " + packet.get(TcpPacket.class).getHeader().getAcknowledgmentNumberAsLong());

I get the following output (I stripped of not relevant info from the packet print out): 

    [TCP Header (32 bytes)]
     Source port: 46070 (unknown)
     Destination port: 3306 (unknown)
     Sequence Number: 2592380009
     Acknowledgment Number: 1222304412
   
    getAcknowledgementNumber 1222304412
    getAcknowledgementNumberAsLong 1222304412

    [TCP Header (32 bytes)]
     Source port: 3306 (unknown)
     Destination port: 46070 (unknown)
     Sequence Number: 1222304412
     Acknowledgment Number: 2592380074

    getAcknowledgementNumber -1702587222
    getAcknowledgementNumberAsLong 2592380074

What suprises me is that the getAcknowlegdementNumber is negative, but using the ..AsLong() function it is exactly the same as in the packet print out. 

I don't understand the logic, so am curious if this behaviour is expected?

To give a bit more context:
I run a query in a MySQL client. This returns multiple packets. The first packet of the request is always where getAcknowledgmentNumber() == getAcknowledgementNumberAsLong().
Coincidentallly it is something very helpful to me, but I am not sure if this is as expected.

Regrads,
Chris

**Comment by Nedro** [comment]
Hello,

The second Acknowledgment Number is causing an overflow because it is too big for an unsigned integer. Highest possible positive value without an overflow is (2^31)-1.
It shows correct for the long because a long can handle bigger numbers.

Greetings Nedro

**Comment by kaitoy** [comment]
It's expected behavior.
The acknowledgement number field in TCP packets is unsigned int but TcpPacket class stores it in a signed int field because Java doesn't have unsigned type.
So, it sometimes overflows and getAcknowledementNumber() returns a negative number.
