### ISSUE TITLE
Can it be possible to set the packet size to a fixed value(via padding)?

### ISSUE THREAD

**Issue by linsergit** [kaitoy/pcap4j#162]
I mean sometimes we'd like to a fixed length packet, in such case after the packet are built up, padding is needed at the trail of packet raw.

In current pcap4j, for the packet classes like UDP who have the payload field, we can set the padding bytes to payload to solve this problem. but for those packet implementations without payload field like ARP, it is impossible to make the packet raw in a fixed length meanwhile keeping the whole packet legal(some field like checksum, total length need to be re-calculated after padding).

Is there any solution for this purpose? I'm really looking forward this feature if it can not be true today.

**Comment by kaitoy** [comment]
If you are on Ethernet network, EthernetPacket.pad would be the solution.

**Comment by linsergit** [comment]
Hi Kaitoy,

No, the EthernetPacket.pad can not solve this problem.

it eventually extends the packet to the length I expected via padding bytes at the tail of raw, but it does NOT change the relevant fields in the packet, like the "total length" of Ipv4. 

Here is the my test packet raws:
My expectation
----------------------------------------
Ethernet packet header:
[Ethernet Header (14 bytes)]
  Destination address: 00:11:22:33:44:01
  Source address: 00:11:22:33:44:11
  Type: 0x8100 (IEEE 802.1Q VLAN-tagged frames)

Ethernet packet payload:
[IEEE802.1Q Tag header (4 bytes)]
  Priority: 0
  CFI: 0
  VID: 20
  Type: 0x0800 (IPv4)
[IPv4 Header (20 bytes)]
  Version: 4 (IPv4)
  IHL: 5 (20 [bytes])
  TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
  **Total length: 118 [bytes]**
  Identification: 0
  Flags: (Reserved, Don't Fragment, More Fragment) = (false, false, false)
  Fragment offset: 0 (0 [bytes])
  TTL: 64
  Protocol: 61 (unknown)
  Header checksum: 0x5e35
  Source address: /13.10.1.2
  Destination address: /13.10.1.1
[data (98 bytes)]
  Hex stream: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

the total length is 118 bytes, it should include the padding bytes at tail.

this is the packet I use EthernetPacket.pad()
------------------------------------------------------
Ethernet packet header:
[Ethernet Header (14 bytes)]
  Destination address: 00:11:22:33:44:01
  Source address: 00:11:22:33:44:11
  Type: 0x8100 (IEEE 802.1Q VLAN-tagged frames)

Ethernet packet payload:
[IEEE802.1Q Tag header (4 bytes)]
  Priority: 0
  CFI: 0
  VID: 20
  Type: 0x0800 (IPv4)
[IPv4 Header (20 bytes)]
  Version: 4 (IPv4)
  IHL: 5 (20 [bytes])
  TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
  **Total length: 20 [bytes]**
  Identification: 0
  Flags: (Reserved, Don't Fragment, More Fragment) = (false, false, false)
  Fragment offset: 0 (0 [bytes])
  TTL: 64
  Protocol: 61 (unknown)
  Header checksum: 0x5e97
  Source address: /13.10.1.2
  Destination address: /13.10.1.1

the "total length" of Ipv4 is still the minimum valid value 20, even though we have the extra 98 padding bytes at tail of packet.

**Comment by kaitoy** [comment]
Ipv4's totalLength always doesn't include Ethernet padding
