### ISSUE TITLE
Creating nif prints four zeroes on Windows.

### ISSUE THREAD

**Issue by subylan** [kaitoy/pcap4j#165]
I'm pretty sure these are some debug prints. Considering they are found when the example code on the website is run, bit frustrating that they're still in the current stable.

Any 1.7.4 release to get rid of these four zeroes? They're not passed through a Logger, so can't disable them either:

![image](https://user-images.githubusercontent.com/17656637/39318350-cf281f22-4975-11e8-912d-2c68f22ea69c.png)

**Comment by kaitoy** [comment]
It's already removed.
https://github.com/kaitoy/pcap4j/commit/b4295df6307c5c86f82ae24be4d2be85c7707516
