### ISSUE TITLE
inaccurate delay

### ISSUE THREAD

**Issue by yersinjacob** [kaitoy/pcap4j#166]
I am using pcap4j to delay the packages for a certain time but I have not managed to be exact there is always an extra time and I do not know if it is for the library or the way I work to dispatch the packages (for example if I say 1000ms the program delays 1040 or 1050 is imprecise).
with the following code I compare every millisecond if it is time to dispatch the packages.

void veriftime(){
        if (qa.size()!=0){ 
            Cpacket cp=(Cpacket)qa.peek();
            if (System.currentTimeMillis()>= cp.getTllegada()+delay){
                try {
                    handlenifb.sendPacket(cp.getPacket());
                    qa.poll();

**Comment by kaitoy** [comment]
I don't think you can delay packets exactly for a certain time because there always would be some overhead.
