### ISSUE TITLE
EthernetPacket.pad() can not make the packet valid in right way

### ISSUE THREAD

**Issue by linsergit** [kaitoy/pcap4j#167]
Hi Kaitoy,

The original issue is closed at "Can it be possible to set the packet size to a fixed value(via padding)? #162:, so i created a new one for the same issue.

you mentioned that the EthernetPacket.pad can help set a packet to a fixed length. but i guess the EthernetPacket.pad can NOT solve this problem correctly.

it eventually extends the packet to the length I expected via padding bytes at the tail of raw by calling ethernetPacket.pad, but it does NOT change the relevant fields in the packet, like the "total length" of Ipv4.

Here is the my test packet raws:
My expectation
------------------------------------------------
Ethernet packet header:
[Ethernet Header (14 bytes)]
Destination address: 00:11:22:33:44:01
Source address: 00:11:22:33:44:11
Type: 0x8100 (IEEE 802.1Q VLAN-tagged frames)

Ethernet packet payload:
[IEEE802.1Q Tag header (4 bytes)]
Priority: 0
CFI: 0
VID: 20
Type: 0x0800 (IPv4)
[IPv4 Header (20 bytes)]
Version: 4 (IPv4)
IHL: 5 (20 [bytes])
TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
Total length: 118 [bytes]
Identification: 0
Flags: (Reserved, Don't Fragment, More Fragment) = (false, false, false)
Fragment offset: 0 (0 [bytes])
TTL: 64
Protocol: 61 (unknown)
Header checksum: 0x5e35
Source address: /13.10.1.2
Destination address: /13.10.1.1
[data (98 bytes)]
Hex stream: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

the "total length" in Ipv4 is 118 bytes, it should include the padding bytes at tail.

this is the packet I use EthernetPacket.pad()
---------------------------------------------------
Ethernet packet header:
[Ethernet Header (14 bytes)]
Destination address: 00:11:22:33:44:01
Source address: 00:11:22:33:44:11
Type: 0x8100 (IEEE 802.1Q VLAN-tagged frames)

Ethernet packet payload:
[IEEE802.1Q Tag header (4 bytes)]
Priority: 0
CFI: 0
VID: 20
Type: 0x0800 (IPv4)
[IPv4 Header (20 bytes)]
Version: 4 (IPv4)
IHL: 5 (20 [bytes])
TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
Total length: 20 [bytes]
Identification: 0
Flags: (Reserved, Don't Fragment, More Fragment) = (false, false, false)
Fragment offset: 0 (0 [bytes])
TTL: 64
Protocol: 61 (unknown)
Header checksum: 0x5e97
Source address: /13.10.1.2
Destination address: /13.10.1.1

the "total length" of Ipv4 is still the minimum valid value 20, even though we have the extra 98 padding bytes at tail of packet, this 98 extra bytes should be treated as payload of Ipv4 so that the "total length" need caculate its length.

**Comment by linsergit** [comment]
Furthermore, it the packet java implementation has the "payload" property, user can add the extra padding in this payload property, then it can fix this issue. 

But I found just few of the existing packet implementations holding payload/payloadBuilder property, like IcmpV4EchoPacket, it has payload, but IcmpV4InformationReplyPacket has no, what's the purpose of the different implementations between them?

**Comment by linsergit** [comment]
Hi Kaitoy,

Any idea about this issue? please go though it when your have time.

Furthermore I got a new idea to solve it and may need you comment about it, which is implementing the 
**payloadBuilder** method in AbstractPacket, currently it's a non-supported method and need subclass to override it:

@Override
    public AbstractBuilder payloadBuilder(Builder payloadBuilder) {
      throw new UnsupportedOperationException();
    }

if we implement this method, all sub-classes are capable to set a payload so that the whole packet can be concatenated with a bytes array to become a wanted fixed length , meanwhile no code change is needed for any existing sub class.

**Comment by Wsky51** [comment]
Hi Kaitoy
Is it ok to implement this function in AbstractPacket class?I also need this function to set the fixed packet length.and my implement are as follows:
```
public abstract class AbstractPacket implements Packet {
    ...
    private final LazyValue<Packet.Builder> payloadBuilderCache;
    public AbstractPacket() {
    ...
        this.payloadBuilderCache= new LazyValue<Packet.Builder>( 
            new BuildValueCommand<Packet.Builder>() {
                 @Override
                 public Packet.Builder buildValue() {
                     return buildPayloadBuilder();
                 }
             }
        );
    }
    protected Packet.Builder buildPayloadBuilder() {
        return getBuilder().getPayloadBuilder();
    }
    @Override
    public Packet getPayload() {
        return payloadBuilderCache.getValue().build();
    }
    public static abstract class AbstractBuilder implements Builder {
        private Packet.Builder payloadBuilder;
        @Override
        public AbstractBuilder payloadBuilder(Builder payloadBuilder) {
            this.payloadBuilder = payloadBuilder;
            return this;
        }
        @Override
        public Builder getPayloadBuilder() {
            return payloadBuilder;
        }
    }
}
```
BR
Wu Yi

**Comment by kaitoy** [comment]
I don't remember very well but I think IcmpV4EchoPacket has a payload but IcmpV4InformationReplyPacket  doesn't according to the RFC, which is the reason of the difference.

"total length" of IPv4 includes only IPv4 header and its payload.
Etherpacket's pad is in neither of them. It's in Ethernet trailer.
Because Ethernet is a lower layer than IPv4, IPv4 never knows about it.
