### ISSUE TITLE
org.pcap4j.core.PcapNativeException: bad dump file format

### ISSUE THREAD

**Issue by gilbertoolimpio** [kaitoy/pcap4j#169]
Hello

I'm trying to read a .pcap file made available at [University of New Brunswick](http://www.unb.ca/cic/datasets/ids-2017.html). I'm trying to read the _Wednesday-workingHours.pcap_ file that has 13Gb and with more than 11 million packages. The exception is thrown at the following point in the code (pcapFile is a String with a path to _pcap_ file):

```
try {
         handle = Pcaps.openOffline (pcapFile, PcapHandle.TimestampPrecision.NANO);
} catch (PcapNativeException e) {
         handle = Pcaps.openOffline (pcapFile);
}

```
I can open the file normally in wireshark.

Where am I going to err to launch this exception?

**Comment by gilbertoolimpio** [comment]
Hello guys

I found the solution! Apparently, despite being a .pcap file it is actually not a pcap file! =)
To resolve this, I had to execute a parse of the file by executing the following command line:
```
editcap -F libpcap {input file name} {output file name}

```
I did this and my program ran again!

More information on this [thread](https://www.winpcap.org/pipermail/winpcap-users/2007-April/001795.html)

**Comment by kaitoy** [comment]
Thank you for your nice information!
