### ISSUE TITLE
How to set packet to a given length except to call EthernetPacket.pad() 

### ISSUE THREAD

**Issue by leomaatEric** [kaitoy/pcap4j#171]
Hi Kaitoy,

I recreate this issue again, the original one is closed at https://github.com/kaitoy/pcap4j/issues/167.

So go ahead and say, there are two different use cases for how to make the packet length to a fixed number between our ideas.

for example, if we need a 100 bytes length packet consists of Ethernet/Ipv4/Icmpv4,

In your opion, it can be:
|<---14 bytes--->|<------20 bytes---------|<---------12 bytes --------->|<------------54 bytes-------->| 
|-----Ethernet---- |--------- Ipv4----------- |--icmpv4 InformationReply--|----------extra bytes----------|
|-------------------|-----------------------ipv4.total_length = 32-----------|-------------ether.pad---------|

My opion is:
|<---14 bytes--->|<------20 bytes---------|<---------12 bytes --------->|<------------54 bytes-------->| 
|-----Ethernet---- |--------- Ipv4----------- |--icmpv4 InformationReply--|----------extra bytes----------|
|-------------------|--------------------------------ipv4.total_length = 86-----------------------------------|

I think above both are rational, the different is only how we treat the extra bytes, as part in ipv4's payload, or as ethernet's pad.

Now my work is blocked by the second case, I'm using pcap4j to replace some commercial product, like Ixia traffic generator, which can build the packet as user wish, the problem is Ixia works as the second case above to set the packet to a fixed length.

I'm seeking a way in pcap4j to solve the second case, so may need you idea about it.

Thanks in advanced.

**Comment by kaitoy** [comment]
Thanks for your explanation. I've got it.
For the second case, because ICMP Information Reply packet doesn't have payload and is fixed length according to [RFC792](https://tools.ietf.org/html/rfc792), the extra bytes need to be included in IPv4 header.

IPv4 header has options field which can be filled by zeros (IpV4EndOfOptionList) or ones (IpV4NoOperationOption).
You can use this field for the second case, but note that IPv4 header needs to be multiple of 4 octets.

**Comment by kaitoy** [comment]
Or, if you don't need to comply with the RFC, you can simply use UnknownPacket instead of IcmpV4InformationReplyPacket and let it have any length of data with any contents.
Such a packet may be discarded or wrongly interpreted at an intermidiate device or the receiver, though.

**Comment by leomaatEric** [comment]
I guess ipv4 header options can not solve the second case, 
it will make the packet look like:
|<---14 bytes--->|<----------20 bytes---------|<---------54 bytes --------->|<----------12 bytes-------->|
|-----Ethernet----|---Ipv4 (option excluded)---|----ipv4 option (zeros) ------|--icmpv4 InformationReply-|
|------------------|--------------------------------ipv4.total_length = 86--------------------------------------|

in my case, the "extra bytes"  are located at the tail of original packet. 

UnknowPacket may be an possible way, but it make no sense for current usage, i mean, theoretically i can built the whole packet with raw byte array, considering Unknowpacket is just hold a "rawData" property

**Comment by leomaatEric** [comment]
As you said informationReply have no payload in RFC, so in this case the extra bytes and informationReply are combined to be the ipv4's payload in this case. i'm not sure if this is comply with the RFC.(maybe not I also think) but it is the way how the Ixia works in my testing.

**Comment by kaitoy** [comment]
ipv4 (and any other protocols I've ever seen) can have only one payload, which is informationReply packet.

**Comment by leomaatEric** [comment]
I'm not saying ipv4 can have "two" payloads.
From the upper level protocol's perspective like ipv4, it can just treat the bytes following its header as its payload, that is also saying, ipv4 can extract the following (ipv4.total_length - ipv4.ihl) length data as its payload. As to this payload itself, ipv4 does not know it actually contains two parts: an informationReply and few extra bytes.

And as you mentioned, get raw bytes from informationReply then concatenate with the extra byte can be a solution for this case, I may try it.

**Comment by kaitoy** [comment]
I meant ipv4 can have only one part of payload.

**Comment by leomaatEric** [comment]
Yes, based on RFC it is. 
The thing is Ixia product provides such feature to extend the packet length to a fixed value via attaching extra bytes at the tail meanwhile including it into ipv4's payload, so somehow it breaks the RFC rules.

**Comment by kaitoy** [comment]
You can build informationReply + extra bytes first and then an IPv4 packet followed by it so that IPv4 can calculate its total length including the "informationReply + extra bytes".
