### ISSUE TITLE
How to run in sudo(root) mode?

### ISSUE THREAD

**Issue by koolmano** [kaitoy/pcap4j#172]
Hi, Kaitoy. I'm creating something with your library and need to debug it. So, it is running in Netbeans. But for example your function  NifSelector().selectNetworkInterface(); needed to be run in sudo(root) mode. How to run this example in Netbeans in root mode on linux platform?

**Comment by guglielmomoretti** [comment]
Hi @koolmano. You just need to give netbeans root permissions. Run Netbeans from the command line using sudo.

Best Regards

**Comment by koolmano** [comment]
thank you.

**Comment by koolmano** [comment]
Hi, guglielmomoretti, I tried to run Netbeans under sudo, but this seems not that easy thing to do, because I think some libraries installed under another path.

**Comment by guglielmomoretti** [comment]
Have you tried this?

`gksu netbeans`

or 

`sudo netbeans`

**Comment by koolmano** [comment]
yeah, but it refuse to open or even create java projects. Some exception occured.

**Comment by koolmano** [comment]
without hard hacking it hard to tell. Unfortunately don't have time for this yet.

**Comment by koolmano** [comment]
It can played hard, you know. guglielmomoretti. For example, just attack gdb to the Netbeans and inject sudo with any password when java jvm launched.

**Comment by kaitoy** [comment]
@koolmano 
Please try to add capabilities as per [this](https://github.com/kaitoy/pcap4j#others).

**Comment by koolmano** [comment]
Hi, kaitoy, good library you've created. Very structural. Design patterned. But how to get IP and TCP packet?  How to create it? Packets.  Packets.containsIpPacket(packet) don't return even when tcp packet comes. You gave us good examples, Can you give us one more example how to get IP and Tcp packet?

**Comment by kaitoy** [comment]
You just need to add a packer factory (pcap4j-packetfactory-propertiesbased.jar or pcap4j-packetfactory-static.jar) to your classpath in order to enable packet dissection, otherwise Pcap4J always returns UnknownPacket that includes a plain byte array for each packet captured.
