### ISSUE TITLE
Packets.containsIpV4Packet never return true even if it tcp packet?

### ISSUE THREAD

**Issue by koolmano** [kaitoy/pcap4j#173]
Looks like this snipped of code never return true for tcp packets.
Packets.containsIpV4Packet(packet).  
this snipped catched packets all right but what about determinig what kind of packet it was?
PacketListener listener
            = new PacketListener() {
            @Override
            public void gotPacket(Packet packet) {
....?
And why Packet was named when actually it have only header inside?

**Comment by kaitoy** [comment]
You need to add a packet factory (pcap4j-packetfactory-static.jar or pcap4j-packetfactory-propertiesbased.jar) to your classpath in order to enable packet dissection, otherwise always packet will be UnknownPacket.
