### ISSUE TITLE
Simple question on how to use pcap4j

### ISSUE THREAD

**Issue by shiv-365** [kaitoy/pcap4j#177]
Hi Kaito,

I am a student and am working on a passion project that deals with checking network and packet traffic. Simply put, I want to make an app with Java, Spring, Spring-boot, and ionic for front end that shows who is on my network and how many packets of data they are transferring. 

I made a simple packet capture application that is based on some of the examples you provided, I can send you the code if you would like to see but the gist of it is to track a large number of packets and put that into an output.pcap file. I am not sure how to go about reading from the .pcap file and I also get a permission denied when I run the app and try to save the packets to the file. 

I am using IntelliJ IDE and Java 8. Additionally, I am trying to learn about Wireshark and how I could use that in conjunction with the pcap4j in IntelliJ. 

I will continue to work on it but any insights that you could give me would be greatly beneficial. Hope to hear from you soon. 

Thanks! 
Shivam

**Comment by shiv-365** [comment]
update: i ran it as sudo and it worked! I got a nice stream of 9000 packets with some data like this: 

`2018-07-18 14:07:28.922096
[data (398 bytes)]
  Hex stream: f0 9f c2 1d 4b 6f 60 f8 1d cb 6b 44 08 00 45 00 01 80 00 00 40 00 40 06 85 f7 c0 a8 03 6b cc 0b 23 62 d1 d3 00 50 21 28 50 45 7a c6 14 bb 80 18 10 00 2a 56 00 00 01 01 08 0a 31 09 5c bc 2e 5b d4 b3 47 45 54 20 2f 6a 73 2f 68 6f 6d 65 70 61 67 65 2e 61 2e 70 `

not sure how to use this data. is there a way to make this hex readable?

**Comment by jvmk** [comment]
> I am not sure how to go about reading from the .pcap

This example shows how to read from a pcap file: https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-sample/src/main/java/org/pcap4j/sample/ReadPacketFile.java

**Comment by shiv-365** [comment]
got it thanks! Now @jvmk do you know how I can connect a spring server to an existing project? I want to have that data dump to a mySQL db and have another server connected to that same db to collect and access it after storing the decrypted packets to it. 

I have to use run mvn package as root user so i am unsure of how that will interact. Could I make a new project and connect it with my PCAP project somehow?

Thanks!

**Comment by allnash** [comment]
@shiv-365 when you are successful, can you provide an example to capture and parse at the same time for probe request?

**Comment by shiv-365** [comment]
@allnash thats what i am trying to figure out with Spring. I have the capture run and then after the springboot starts up. I am not sure how to do it concurrently. Any ideas?

**Comment by allnash** [comment]
I think Java futures?
Or concurrent lists or hashmaps

Sent from my iPhone

On Jul 20, 2018, at 1:01 PM, shiv-365 <notifications@github.com<mailto:notifications@github.com>> wrote:


@allnash<https://github.com/allnash> thats what i am trying to figure out with Spring. I have the capture run and then after the springboot starts up. I am not sure how to do it concurrently. Any ideas?

**Comment by jvmk** [comment]
> got it thanks! Now @jvmk do you know how I can connect a spring server to an existing project? I want to have that data dump to a mySQL db and have another server connected to that same db to collect and access it after storing the decrypted packets to it.
>
>I have to use run mvn package as root user so i am unsure of how that will interact. Could I make a new project and connect it with my PCAP project somehow?
>
>Thanks!

Not really sure what you're asking, sorry. You can include the pcap4j library into any maven-based project by adding it as a dependency, so I don't see any problem in creating a new project and incorporating your pcap4j-based code into that one.

I'm not familiar with Spring, sorry. However, the question sounds more like a (mySQL- + web-) server configuration kind of question than a framework question.
