### ISSUE TITLE
loss SIP header's data in TcpPacket [TCP Reassembled]

### ISSUE THREAD

**Issue by AhmedCPS** [kaitoy/pcap4j#179]
when initialize TcpPacket and get PayLoad of packet ,  SDP which it's body of SIP header appear ,  but SIP header's data once appear and another lost and sometimes appear part of sip Header not all data how to solve it because i use SIP data ?

**Comment by kaitoy** [comment]
TcpPacket represents a TCP packet, which is a piece of upper layer data.
In order to get the upper layer data, you need to reassemble it from some TcpPacket payloads.
