### ISSUE TITLE
How do you get data through streams instead of packets?

### ISSUE THREAD

**Issue by tyx11111** [kaitoy/pcap4j#180]
just like (follow tcp stream)\(follow udp stream)\(follow ssl stream) in wireshark

Hope to get your answer,thanks

**Comment by kaitoy** [comment]
A stream is a sequence of packets, and Pcap4J can capture such packets.
But, in a stream, its upper layer data is divided and so you need to reassemble the data from packets Pcap4J captured.
Currently Pcap4J doesn't provide a feature to help it.
