### ISSUE TITLE
PcapPcaket: length() vs. getOriginalLength()

### ISSUE THREAD

**Issue by jvmk** [kaitoy/pcap4j#186]
Hello there!

First of all, thank you for a very useful library that is a joy to use!

I have a simple question, please: in `PcapPacket`, what is the difference between `length()` and `getOriginalLength()`?

**Comment by kaitoy** [comment]
Thank you for using Pcap4J!

Pcap4J doesn't capture always the whole part of a packet.
It instead captures a certain number of bytes at most, which is specified by `PcapNetworkInterface#openLive()`'s snaplen.
So, `length()` returns the number of bytes captured in Java world (i.e. maybe a part of a whole packet), and `getOriginalLength()` returns the number of bytes the network interface received.

**Comment by kaitoy** [comment]
Yes, you right.

**Comment by ohuseyinoglu** [comment]
In a test (to see if any packet reaching my code was truncated), on a Loopback adapter on Windows (npcap 0.99-r9) (snapLen = 64K), I've noticed that for byte array returned from `getNextRawPacketEx` the relationship b/w these 2 values are `OriginalLength = (2 x length - 4)`!? There shouldn't be any wide-char kind of conversion or anything like that, right? Any insight on that?
