### ISSUE TITLE
 support HTTP packet ？

### ISSUE THREAD

**Issue by bdliang** [kaitoy/pcap4j#187]
#85 
https://gist.github.com/kaitoy/2aca1d6b8644fcccf0cfa5d30f5fe573  the page can not access ，ERR_CONNECTION_TIMED_OUT。

**Comment by kaitoy** [comment]
Pcap4J doesn't support HTTP yet.
Because HTTP is over TCP and TCP fragments upper layer packets, Pcap4J needs to support TCP reassembly before it can dissect HTTP packets.
Pcap4J doesn't support TCP reassembly neither...

BTW, I can access the page now.
Please try again.
