### ISSUE TITLE
Problems with log4j

### ISSUE THREAD

**Issue by swirlsky** [kaitoy/pcap4j#193]
```
log4j:WARN No appenders could be found for logger (org.pcap4j.core.NativeMappings).
log4j:WARN Please initialize the log4j system properly.
```
This is written on the console when I use the library in my Java application.
Is there a way to disable the logging entirely for the package org.pcap4j?

**Comment by swirlsky** [comment]
[I posted it on StackOverflow](https://stackoverflow.com/q/53430871/5214911) too, someone might have an idea.

**Comment by kaitoy** [comment]
Pcap4J uses SLF4J for logging.
You can disable its logging by adding slf4j-nop.jar to your classpath.
Please refer to SLF4J document: https://www.slf4j.org/manual.html#swapping
