### ISSUE TITLE
pcap file with truncated packet

### ISSUE THREAD

**Issue by frojasg1** [kaitoy/pcap4j#198]
Hello,

I am new to using your library and I wonder if it is possible to read a pcap file which has been truncated.
Of course, I do not pretend to decode the last packet, but:
Is there any way to decode de preceeding packets?

The error I am getting is:

    org.pcap4j.core.PcapNativeException: truncated dump file; tried to read 24 file header bytes, only got 0
	at org.pcap4j.core.Pcaps.openOffline(Pcaps.java:210) ~[classes/:na]

Line number do not match the one of the source code, because I have modified the sources to try to avoid the exception.

I will look forward your answer.

you can download the pcap used for the test here:
http://www.frojasg1.com/small.pcap

thanks,
Fran.

**Comment by kaitoy** [comment]
I don't think so...

The error you put came from the native library that pcap4j wraps.
Pcap4J can't control nor avoid such an error.
