### ISSUE TITLE
PcapHandle::close() deadlock

### ISSUE THREAD

**Issue by hauges** [kaitoy/pcap4j#199]
I am currently running into an issue where I am seeing deadlock when calling `PcapHandle::close()`. This issue is only seen if the packets are ever actually captured by the `PcapHandle` I am trying to close. If there are captured packets, there is no deadlock.

Here is a condensed/simplified version of my code:
```
PcapHandle pcapHandle;
// Initializationn

void loop() {
    // Call to pcapHandle.loop()
}

void close() {
    pcapHandle.breakLoop();
    pcapHandle.close();  // This is where I see deadlock
}
```

I've tried sending bogus packets per the suggestion in `PcapHandle::breakLoop()` javadocs, both before and after my call to `PcapHandle::breakLoop()` (_i.e._ `pcapHandle.sendPacket(someBogusPacket)`), but this does not work. 

Like I said before, this issue only occurs if no packets are captured in `pcapHandle.loop()`.

I should also add that `pcapHandle.loop()` is running in its own thread, so that method is not what is blocking.

**Comment by hauges** [comment]
Update: Even if I run `pcapHandle.close()` in its own thread with a timeout, the next `PcapHandle` I try to call `breakLoop()` on deadlocks inside that method (I am running multiple `pcapHandle.loop()` on different instances of `PcapHandle`. Could there be a lock used in your native methods that are never released even if the java function running it errors out?

**Comment by hauges** [comment]
Yes, I am calling `breakLoop()` in another thread, and then I am calling `close()` in that thread as well. Why would I need to call `loop()` again?

**Comment by kaitoy** [comment]
No, you don't need to call loop() twice.
I suspect that packets sent by `pcapHandle.sendPacket(someBogusPacket)` are not captured by the pcap handle.
For example, if the destination address of the packets are the same as the machine that runs Pcap4J, the packets are handled by the loopback interface and not captured by the pcap handle.

'loop()' sometimes behave weirdly, so it may be better to use 'PcapHandle#getNextPacketEx()' instead in a while loop.

**Comment by hauges** [comment]
I was hoping to avoid having to control the loop in my code, but for now it looks like `PcapHandle#getNextPacketEx()` works with a loop.

**Comment by kaitoy** [comment]
I'm glad to hear that.
I close this.
