### ISSUE TITLE
After getting a GTP Packet the payload is untyped

### ISSUE THREAD

**Issue by Yufiel** [kaitoy/pcap4j#205]
Hi,
I'm looking at a GTP Packet payload and everything is a unknown packet. 
But I expected an IP Packet and an UDP (or TCP) Packet (https://en.wikipedia.org/wiki/GPRS_Tunnelling_Protocol)

![screenshot from 2019-02-12 11-54-12](https://user-images.githubusercontent.com/584219/52630608-fcb59a00-2ebc-11e9-8f99-592e13b56c54.png)

I access the handle simply with:
GtpV1Packet gtpV1Packet = packet.get(GtpV1Packet.class);

**Comment by kaitoy** [comment]
Pcap4J doesn't support parsing payloads of GTP...
