### ISSUE TITLE
Why not synchronize org.pcap4j.core.Pcaps.findAllDevs()?

### ISSUE THREAD

**Issue by solind** [kaitoy/pcap4j#210]
If the method is not thread-safe, as the documentation states, why not just synchronize access to it?

**Comment by kaitoy** [comment]
Do you see any error when you use it in multi threads?
I think its already thread-safe.

**Comment by solind** [comment]
The Javadoc comment for the method indicates it isn't thread-safe.  Looking at the implementation, I don't see why it wouldn't be, but I'm not a JNA expert.

I did run into a situation in a multi-threaded application where I:
1) Got a PcapNetworkInterface using an InetAddress
2) Got an InetAddress from PcapNetworkInterface.getAddresses()[X].getAddress() (starting from the interface fetched in step 1), and then later...
3) Failed to find the original PcalNetworkInterface using the same address and the Pcaps.getDevbyAddress method (it returned null)

This could be explained if all the threads were using some common buffer at the same time, but it's certainly possible that something else was happening as well.  But the Javadoc comment made me suspicious.

**Comment by kaitoy** [comment]
Ah, sorry, I've forgotten it.
I added such a javadoc comment to respond to [an issue](https://github.com/kaitoy/pcap4j/issues/157).
The native method wrapped by `findAllDevs` is not thread-safe, so `findAllDevs` is not, too.

I don't think `findAllDevs` is a method that people in most cases want to call in multiple threads.
If want, they can synchronize outside of `findAllDevs`.
I think this is reasonable.

**Comment by solind** [comment]
Absolutely!  Indeed, that is also the work-around I am now using.

I am only suggesting, if you added the keyword ```synchronized``` to the method declaration of Pcaps.findAllDevs(), that would prevent the issue from ever arising for anyone.

**Comment by kaitoy** [comment]
Thanks for your suggestion.
I created a commit to improve `Pcaps.findAllDevs()` to be thread-safe.
