### ISSUE TITLE
Issue with byte type of payload

### ISSUE THREAD

**Issue by lennartkoopmann** [kaitoy/pcap4j#211]
First of all, thank you for the great work on this project.

I have a use-case where I just manually want to slice a part out of a 802.11 payload `byte[]` and this works well. I am hitting a problem though, where a value of a byte is larger than 128 in the 802.11 specs and the Java `byte` wraps around to `-127`. Have you ever hit that limitation? Any pointers on what I could do?

**Comment by kaitoy** [comment]
Thank you for using Pcap4J.

You can cast the byte value to int like: `int intVal = 0xFF & byteVal;`

**Comment by lennartkoopmann** [comment]
Ah, of course. I even used that in another place already and don't know why I blacked out here. Thank you so much!
