### ISSUE TITLE
Proguard Implementation

### ISSUE THREAD

**Issue by eakteam** [kaitoy/pcap4j#212]
Hello, thanks for this great library. 
Can you please suggest best keep rules to apply when using proguard ? I throws exception if we don't keep all packet class. But keep option is heavy, it keeps everything.
So is there any suggestion for proguard best use ?
Best Regards

**Comment by kaitoy** [comment]
Thank you for your interest in Pcap4J.

I've never used ProGuard and don't have any knowledge about it.
But I guess you need to include packet classes one by one as you see exceptions.
Pcap4J's packet dissector is very dynamic, so I don't think ProGuard can know which classes are actually needed at compile time.
