### ISSUE TITLE
Meaning of "INFO org.pcap4j.core.PcapHandle - Broken" log output

### ISSUE THREAD

**Issue by jvmk** [kaitoy/pcap4j#215]
Hi kaitoy,

Thanks for providing a great library, it's really a fantastic tool!

I'm using pcap4j to perform live captures using the  provided `PcapHandle.openLive()`, `PcapHandle.loop(`) and `PcapHandle.breakLoop()` methods. I do a series of captures sequentially like so:

1. Start a live capture on `wlan0` that dumps packets to `file1.pcap`. Then leave this running for a while, and finally terminate the capture by calling `PcapHandle.breakLoop()`.
2. Same as above, but dumping to `file2.pcap`.
3. Same as above, but dumping to `file3.pcap`.
4. Etc.

I've noticed that when I start capture 2, 3, 4 etc., I get log output that says `[Thread-X] INFO org.pcap4j.core.PcapHandle - Broken.` for the previous capture (the `X` is the thread responsible for the previous capture, e.g., the thread responsible for capture 1 when I start capture 2).

What exactly does this output mean? Should it concern me? I successfully produce meaningful `.pcap` files, but some of them generate the warning _"The capture file appears to have been cut short in the middle of a packet"_  when opened in Wireshark. I think that this is probably just an artifact of the underlying native packet capture being terminated abruptly, resulting in the last packet being cut short (and that I can simply drop the last packet of these captures)...?

From searching your code, it seems that the log output originates from `PcapHandle.doLoop()` , when the native `pcap_loop()` call returns `-2` (https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-core/src/main/java/org/pcap4j/core/PcapHandle.java). The [man page for `pcap_loop()`](https://linux.die.net/man/3/pcap_loop) states that `-2` will be returned if:

> [...] the loop terminated due to a call to `pcap_breakloop()` before any packets were processed.

While I do use `PcapHandle.breakLoop()` to terminate the capture, this puzzles me as the files do indeed contain packets, so the statement that _"no packets were processed"_ is not really true.

Could you please be so kind to provide an explanation of why this may occur? Should I consider my captures corrupted?

Thanks a lot in advance.

Best,

**Comment by kaitoy** [comment]
Thank you for using Pcap4J.

I looked at the source code of libpcap.
What is returned when `pcap_loop()` is stopped by `pcap_breakloop()` depends on platform.
It looks like `pcap_loop()` always returns -2 when broken on Linux, but, on some other platforms, it returns -2 only when no packets are captured before a break.
I think your case is former and you don't need to concern.
