### ISSUE TITLE
TcpPacket being read as UnknownPacket?

### ISSUE THREAD

**Issue by brilam** [kaitoy/pcap4j#218]
Hello,

I am new to pcap4j so perhaps, I might be using it wrong. But I will try my best to describe the issue I am running into. I am writing a packet sniffer and the packet I am attempting to sniff is a TcpPacket. From my understanding, this snippet should listen for packets:

```PacketListener listener = new PacketListener() {
      @Override
      public void gotPacket(PcapPacket packet) {
        byte packetData[] = packet.get(TcpPacket.class).getPayload().getRawData();
        System.out.println("Received at: " + packet.getTimestamp());
        System.out.println("Header: " + packet.getHeader()); // ???
        System.out.println("Length: " + packet.length());
        System.out.println("Data: " + packet);
        System.out.println(packet.getBuilder());
      }
    };
```

I found that packetData gave a NullPointerException since getPayload() returned null. After a bit of investigating, I tried to figure out what getBuilder() was returning and it said UnknownPacket rather than TcpPacket. Any ideas on what could be wrong? Am I using this incorrectly?

**Comment by ohuseyinoglu** [comment]
Have you set a filter (to capture only tcp packets) on the pcap handle that you set up this listener function for? Unless you've done that pcap (or pcap4j) will have no way of knowing that you're interested only in tcp packets and send you everything passing through the network interface (including UDP, and other IP level protocols). And when these packets are processed, you won't "get" a TcpPacket out of them (i.e. you shouldn't assume you'd always get a Tcp Packet from every data fragment).

(Even if you've set up a filter, there was one case (related to IPv6 loopback) that I've run into where Tcp packet extraction would fail, but let'me not complicate the issue log with that case for now).

**Comment by brilam** [comment]
Thanks for the reply! This is the filter that I've used:

```java
    String filter = "tcp port " + port;
    handle.setFilter(filter, BpfCompileMode.OPTIMIZE);
```

I presume that this should suffice in indicating that the packets to be captured are TCP? I am not quite sure what you mean by you won't "get" a TcpPacket. Do you mean that I will always gets a PcapPacket and that I would have to get the TcpPacket from it?

**Comment by ohuseyinoglu** [comment]
(I was referring to `.get(TcpPacket.class)` part of your code when I said '_you won't "get" a TcpPacket ..._'.)

If you did set a filter like that, you may be running into to the same issue I had! Try getting the raw btyes from the packet, and see if you can make sense of them (running Wireshark in parallel would help with disecting IP, and lower levels).

For my case, I ended up using a workaround like the following:

```java
	private static final int IP_V6_SIGNATURE_BYTE = 0x60;
	private static final int IP_V6_OFFSET = 4;
	private static final int IP_V6_CHECK_MIN_SIZE = 5;
	private static final int IP_V6_PROTOCOL_FAMILY_NUMBER = 0x18;

	private void fixNonTcpPacket() {
		if (!packet.contains(TcpPacket.class)) {
			byte[] packetRawData = packet.getRawData();
			// This usually happens as protocol family in IPv6 loopback adapter as a different (24) protocol family number (than default=23)
			IpV6Packet ipV6Packet = checkGetIpV6Packet(packetRawData);
			if (ipV6Packet != null && ipV6Packet.contains(TcpPacket.class)) {
				// Switch to our newly created packet!
				packet = ipV6Packet;
				return;
			}

			// Failed in conversion... it should be yet another problem with packet structure, and Pcap4J
			logger.error("PACKET W/O TCP!?!\n{}", ByteBufUtil.prettyHexDump(Unpooled.wrappedBuffer(packetRawData)));
			packet = null;
		}
	}

	private IpV6Packet checkGetIpV6Packet(byte[] packetRawData) {
		if (isLoopbackPacketIpV6(packetRawData)) {
			try {
				return IpV6Packet.newPacket(packetRawData, IP_V6_OFFSET, packetRawData.length - IP_V6_OFFSET);
			} catch (IllegalRawDataException e) {
				logger.error("Exception: While converting non-TCP packet to IPv6!", e);
			}
		}
		return null;
	}

	private boolean isLoopbackPacketIpV6(byte[] packetRawData) {
		return ((packetRawData.length > IP_V6_CHECK_MIN_SIZE) && (ByteArrays.getInt(packetRawData, 0, ByteOrder.nativeOrder()) == IP_V6_PROTOCOL_FAMILY_NUMBER)
			&& ((ByteArrays.getByte(packetRawData, IP_V6_OFFSET) & 0xf0) == IP_V6_SIGNATURE_BYTE));
	}

```

As you can see, the key part is this comment: **This usually happens as protocol family in IPv6 loopback adapter as a different (24) protocol family number (than default=23)**

When I wrote this code, I settled with a workaround, and not logged an issue assuming it may be an issue specific to my set-up/HW. If your case is also the same, please do write back on this thread, and we can ask kaitoy for a fix in the library instead of having work-arounds (BTW, as you may have guessed, I'm not the owner, or a contributor of this repo, just a user trying to help! :) ).

**Comment by brilam** [comment]
Yeah, I noticed that you are user trying to help and I appreciate that!

I am not sure if I am going about this the right way. But looking at your code and testing around with Wireshark, I figured out how my packet looks like:

[Ethernet Header][IpV4 Header][TCP Header]

So what I did was I created an EthernetPacket using the data of the UnknownPacket. However, I appear to be running into the issue of creating the IpV4Packet. Here is my code snippet if this helps:

```java
public void startSniffing() throws PcapNativeException, NotOpenException, InterruptedException {
    final PcapHandle handle;
    handle = device.openLive(SNAPSHOT_LENGTH, PromiscuousMode.PROMISCUOUS, READ_TIMEOUT);
    String filter = "tcp port " + port;
    handle.setFilter(filter, BpfCompileMode.OPTIMIZE);

    PacketListener listener = new PacketListener() {
      @Override
      public void gotPacket(PcapPacket packet) {
       
        System.out.println("Received at: " + packet.getTimestamp());
        System.out.println("Received from: " + packet.get(UnknownPacket.class).getHeader());
        System.out.println("Length: " + packet.length());
        
        
        EthernetPacket ethernetPacket = null;
        IpV4Packet ipv4Packet = null;
        try {
          ethernetPacket = convertUnknownPacketToEthernet(packet);
          byte ethernetData[] = ethernetPacket.getRawData();
          System.out.println("Ethernet payload data: " + bytesToHex(ethernetPacket.getPayload().getRawData()));
          convertPacketToIpV4(ethernetPacket.getPayload().getRawData());
        } catch (IllegalRawDataException e) {
          // TODO Auto-generated catch block
          e.printStackTrace();
        }
        System.out.println("Data: " + bytesToHex(ethernetPacket.getRawData()));
        System.out.println("Ethernet Header: " + ethernetPacket.getPayload());
      }
    };
    
   handle.loop(LOOP_INFINITY, listener);
  }

  private EthernetPacket convertUnknownPacketToEthernet(PcapPacket packet)
      throws IllegalRawDataException {
    return EthernetPacket.newPacket(packet.getRawData(), 0, packet.length());
  }
  
  private IpV4Packet convertPacketToIpV4(byte[] ipv4Data) throws IllegalRawDataException {
    return IpV4Packet.newPacket(ipv4Data, 0, ipv4Data.length);
  }```

**Comment by undera** [comment]
I think there is a problem detecting TCP traffic. I face same kind of issue with reading PCAP file.
With version 1.7.7 the code works and detects TCP packet, version 2.0.0-alpha.3 treats it as UnknownPacket.
Exerpt from my code:
```java
        PcapHandle handle;
        try {
            handle = Pcaps.openOffline(argv[0], PcapHandle.TimestampPrecision.NANO);
        } catch (PcapNativeException e) {
            handle = Pcaps.openOffline(argv[0]);
        }

        Map<TcpPort, TcpSession> sessions = new HashMap<TcpPort, TcpSession>();
        while (true) {
            try {
                Packet packet = handle.getNextPacketEx();
                TcpPacket tcp = packet.get(TcpPacket.class);
                if (tcp == null) {
                    continue;
                }

                boolean isToServer = true;
                TcpPort port = tcp.getHeader().getSrcPort();
                // ...
```

**Comment by brilam** [comment]
Thanks for sharing your code @undera I've made some changes to my code accordingly to yours and was testing around. It seems the following would work for both 1.7.7 and 2.0.0 alpha 3 (it works for me!). Perhaps, this may be helpful to you too?

```java
PacketListener listener = new PacketListener() {

      @Override
      public void gotPacket(PcapPacket packet) {
        IpV4Packet ipv4 = packet.get(IpV4Packet.class);
        TcpPacket tcpPacket = packet.get(TcpPacket.class);
        if (tcpPacket == null) {
          System.out.println("Packet is null");
        } else {
          if (tcpPacket.getPayload() != null) {
            System.out.println("Source Address: " + ipv4.getHeader().getSrcAddr());
            System.out.println("Destination Address: " + ipv4.getHeader().getDstAddr());
            System.out.println("Length: " + tcpPacket.length());
            System.out.println("Data: " + tcpPacket.getPayload());
          }
        }
      } 
    };
    handle.loop(LOOP_INFINITY, listener);
```

**Comment by kaitoy** [comment]
@brilam 
You solved your problem? Can I close this?

**Comment by brilam** [comment]
Yes. The problem has been solved. I will close it myself. Thanks!
