### ISSUE TITLE
Can't compile on Linux platform

### ISSUE THREAD

**Issue by freeasbird** [kaitoy/pcap4j#219]
when i use following command on linux

git clone https://github.com/kaitoy/pcap4j.git
cd pcap4j
./mvnw install -Dmaven.test.skip=true

it will give failure feedback.  why? :)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Pcap4J ............................................. SUCCESS [  0.212 s]
[INFO] Pcap4J Core ........................................ SUCCESS [  5.213 s]
[INFO] Pcap4J Packet Test ................................. SUCCESS [  0.027 s]
[INFO] Pcap4J Static Packet Factory ....................... FAILURE [  1.861 s]
[INFO] Pcap4J Properties-Based Packet Factory ............. SKIPPED
[INFO] Pcap4J Sample ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.443 s
[INFO] Finished at: 2019-04-24T20:47:00-07:00
[INFO] Final Memory: 18M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pcap4j-packetfactory-static: Could not resolve dependencies for project org.pcap4j:pcap4j-packetfactory-static:jar:1.7.8-SNAPSHOT: Could not find artifact org.pcap4j:pcap4j-packettest:jar:tests:1.7.8-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pcap4j-packetfactory-static

**Comment by kaitoy** [comment]
It's probably becuase Pcap4J Static Packet Factory depends on the artifact of Pcap4J Packet Test but it wasn't built due to `maven.test.skip=true`.
You can try `./mvnw install` without `maven.test.skip=true` or `./mvnw test-compile && ./mvnw install -Dmaven.test.skip=true`

**Comment by kaitoy** [comment]
Close this for inactivity.
