### ISSUE TITLE
Can't set dlt Raw IP in handle 

### ISSUE THREAD

**Issue by AzKeryon** [kaitoy/pcap4j#221]
Hello, i have this problem that i cant set the dlt of a handle to RAW_IP, by default dlt is EN10MB. Already tried running the code with sudo.
I want to change the dlt because i need to send packets to a interface but i cant work with MACs and ARPs (that is OS responsability).
Please can someone help me understand the error, or is not possible send Raw IP packets with this library?

This was what i do to try to change dlt: 
```
static PcapHandle[] handle;
...
handle[n] = e.openLive(snapshotLength, PcapNetworkInterface.PromiscuousMode.PROMISCUOUS, readTimeout);
handle[n].setDlt(DataLinkType.RAW);
...
```
This is the error i get:
![image](https://user-images.githubusercontent.com/43756835/57181794-50b69600-6e90-11e9-9347-770e43d7cc5a.png)

**Comment by kaitoy** [comment]
I don't think RAW_IP is a DLT to delegate L2 layer protocol handling to a network interface.
It's for interfaces that don't need to handle L2 layer protocol such as loopback interface.
If you want to send packets to L2 connected another machine, you need to know or resolve its MAC address yourself.

**Comment by AzKeryon** [comment]
So i can't change the DLT of that interface to RAW? 
One solution is discover the  MAC address of the host that i want to send a packet, build a new ethernet packet (with destination MAC address that i just discover) and send the packet?

**Comment by kaitoy** [comment]
Yes, that's what I think.
