### ISSUE TITLE
Is hostname resolution done in Pcap4J?

### ISSUE THREAD

**Issue by jtechpro** [kaitoy/pcap4j#222]
I would like to disable the hostname resolution for the Pcap4J.
For example with tcpdump we do it in the following way:

tcpdump -i eth0 -nn

Where, -nn means not to resolve IP and port. This significantly improves performance.

I would like to know if it is the default behavior or anything I need to change in order to enable this flag.
A code snippet would be nice :)

**Comment by kaitoy** [comment]
Pcap4J doesn't do hostname resolutions during packet dissection by default.
