### ISSUE TITLE
Hello, is there any way to avoid losing packets?

### ISSUE THREAD

**Issue by PandaChanV587** [kaitoy/pcap4j#223]
During the monitoring period, I tried to use another thread to cyclically send UDP packets to 1.2.3.4 and use pcap4j's loop to capture the count.
The number of bytes sent per count is not equal to the number of bytes actually sent, and the number of bytes sent each time is not equal.

**Comment by kaitoy** [comment]
You should set snaplen (`PcapHandle.Builder#snaplen(int snaplen)`) and buffersize (` PcapHandle.Builder#bufferSize(int bufferSize)`) to avoid packet losses.

**Comment by PandaChanV587** [comment]
OK, thank you very much，👍
