### ISSUE TITLE
Unable to decode SNMPV3 packet

### ISSUE THREAD

**Issue by jtechpro** [kaitoy/pcap4j#224]
I am capturing the snmp packets and trying to decode the captured byte[].

UdpPacket udpPacket=pcapPacket.get(UdpPacket.class);
udpPacket.getRawData();
and then decoding this data.

decodeV3(data);

There is some problem with headers and the length of the packet.
I would like to know which should be used:

pcapPacket.getRawData() or unknownPacket.getRawData() or udpPacket.getRawData() or ipv4Packet.getRawData();

I have tried all of them but none of them worked..
I have also tried taking the header and raw data as the byte[] and giving the combined byte[] for decoding.. but it did not work.

What is the data (or what method should be called to get the data necessary to decode the snmp packet)?

Thanks in advance.

**Comment by kaitoy** [comment]
`udpPacket.getRawData()` should be what you need.
Packets can be truncated by libpcap. You can check if it's the case by comparing `PcapHandle#getOriginalLength()` and `PcapHandle#getSnapshot()`.
