### ISSUE TITLE
Unable to decode TCP based DNS Query from PCAP

### ISSUE THREAD

**Issue by beyonddc** [kaitoy/pcap4j#226]
Thanks for reading my issue.

I am using pcap4j 1.8.0 and trying to parse a TCP based DNS query from a PCAP file that I obtained from http://packetlife.net/captures/dns-zone-transfer-axfr.cap.  I opened in Wireshark and then saved as pcap file.

The particularly packet that I want to decode is packet 4 and 5 in the pcap file.  Packet 4 is the DNS question and packet 5 is the DNS answer.

I am using the static packet factory, I received a Null object when invoking `packet.get(DnsPacket.class)`

I also tried to manually create the DnsPacket by
```
final TcpPacket tcpPacket = pcap4jPacket.get(TcpPacket.class);
final DnsPacket dnsPacket = DnsPacket.newPacket(tcpPacket.getPayload().getRawData(), 0, tcpPacket.getPayload().getRawData().length); 
```
The result is an IllegalRawDataException for packet 4.
```
org.pcap4j.packet.IllegalRawDataException: The data is too short to build rData of DnsResourceRecord (28525 bytes). data: 00 1c 00 00 00 00 00 01 00 00 00 00 00 00 04 65 74 61 73 03 63 6f 6d 00 00 fc 00 01 4d 53, offset: 12, length: 18, cursor: 11, dataType: 4 (MF (Mail forwarder))
```

For packet 5, the result is the TcpPacket has a null payload.

Is this a bug in pcap4j?  The pcap can be open and view using Wireshark.

**Comment by kaitoy** [comment]
A TCP packet usually carries only a fragment of an upper layer (DNS in this case) packet and so defragmentation is needed to build a DnsPacket.
Pcap4J now doesn't provide such a feature.
