### ISSUE TITLE
No static method toUnsignedInt(S)

### ISSUE THREAD

**Issue by eakteam** [kaitoy/pcap4j#227]
```
Fatal Exception: java.lang.NoSuchMethodError: No static method toUnsignedInt(S)I in class Ljava/lang/Short; or its super classes (declaration of 'java.lang.Short' appears in /system/framework/core-libart.jar)
       at org.pcap4j.packet.factory.statik.StaticEtherTypePacketFactory.newInstance(StaticEtherTypePacketFactory.java:136)
       at org.pcap4j.packet.factory.statik.StaticEtherTypePacketFactory.newInstance(StaticEtherTypePacketFactory.java:26)
       at org.pcap4j.packet.IpSelector.newPacket(IpSelector.java:44)
```

**Comment by kaitoy** [comment]
Your Java is too old.
Pcap4j v2 requires Java 8+.

**Comment by eakteam** [comment]
I am using latest Kotlin and Java 1.8 in my Android App

**Comment by kaitoy** [comment]
It seems Android's Java 8 doesn't support toUnsignedInt that's supported by usual Java 8 such as Oracle Java.
Please use Pcap4J v1 instead, or maybe you can implement toUnsignedInt by Kotlin's Extension Function?

**Comment by eakteam** [comment]
@kaitoy , I will try that thanks, but i think it's better to implement a workaround to handle this automatically directly from the lib itself.
Thanks for your answer

**Comment by eakteam** [comment]
@kaitoy , This is Android official documentation, it is supporting Short.toUnsignedInt actually ...

> Converts the argument to an int by an unsigned conversion. In an unsigned conversion to an int, the high-order 16 bits of the int are zero and the low-order 16 bits are equal to the bits of the short argument. Consequently, zero and positive short values are mapped to a numerically equal int value and negative short values are mapped to an int value equal to the input plus 216.

https://developer.android.com/reference/java/lang/Short#toUnsignedInt(short)

**Comment by kaitoy** [comment]
[This OP](https://stackoverflow.com/questions/37776026/java-short-tounsignedint-not-defined) probably experienced the same problem as yours.
I also found a Japanese blog post that says toUnsignedInt is not implemented in Android Java.

Anyway, I will think about avoiding to use the method.

**Comment by kaitoy** [comment]
Pcap4J 2.0.0-alpha.6 was released with a fix that removes toUnsignedInt.
