### ISSUE TITLE
InfiniBand address extraction causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ohuseyinoglu** [kaitoy/pcap4j#228]
As pointed out in ["BUGS" section](https://linux.die.net/man/8/ifconfig) of `ifconfig`, I believe libpcap also uses "ioctl access method" and this causes an incompatibility with InfiniBand protocol (which uses a 20-byte address). So when `ByteArrays.getSubArray()` is used with length 20 on an array of (hardcoded) 8 bytes (`sockaddr_ll#sll_addr`), we end up with the exception!

In the following line:

https://github.com/kaitoy/pcap4j/blob/5ec441d02188cae8cce1c00ff791d542d51acec5/pcap4j-core/src/main/java/org/pcap4j/core/PcapNetworkInterface.java#L91

You probably want to stay conservative, and not use `addrLength`, but minimum of `addrLength`, and `addr.length`?? Or if libpcap is able to extract all 20 bytes of the address, you may want to extend the size of `sockaddr_ll#sll_addr`??

Thanks!

**Comment by kaitoy** [comment]
Did you see an error actually?
sockaddr_ll.ssl_addr should be always char[8].

https://github.com/torvalds/linux/blob/a978a5b8d83f795e107a2ff759b28643739be70e/include/uapi/linux/if_packet.h#L20

**Comment by ohuseyinoglu** [comment]
It seems the array is defined that way, but for this particular network interface the assignment of `sll_halen` must have been set "incorrectly" as 20 (or correctly as 20, but the array was incorrectly defined to be to small for this particular interface!). In any case, they should have been compatible...

I do see the exception in issue's title with an error message saying:

`arr.length: 8, offset: 0, len: 20, arr: <8-bytes-as-hex>`

Note that, `ifconfig` on the computer with the card emits a warning along the similar lines:

`Infiniband hardware address can be incorrect! Please read BUGS section in ifconfig(8)`

(and when the address is listed below this warning in `ifconfig` output, the last 12 bytes were all zeros)

BTW, just to be clear, I'm not saying this is a "bug" of Pcap4j. It's more like an incompatible setting of values in `sockaddr_ll` struct that's coming from libpcap - so it would make more sense that this is fixed there (or in the OS code/structures you linked), but in anycase, safeguarding our code here in Pcap4j wouldn't hurt, and would result in a much faster resolution I think! :)

**Comment by kaitoy** [comment]
Thanks for your clarification.
I understand the problem. I will think of its fix.

**Comment by kaitoy** [comment]
I made a fix for this issue.
Please try snapshot builds:

* https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.8.2-SNAPSHOT/pcap4j-distribution-1.8.2-20190815.063510-9-bin.zip
* https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j/2.0.0-alpha.6-SNAPSHOT/pcap4j-2.0.0-alpha.6-20190815.070310-5-distribution.zip

**Comment by kaitoy** [comment]
Pcap4J 1.8.2 was released a fix for this issue.
