### ISSUE TITLE
Please adivice an approach to process a TCP packet to get data inside the packet

### ISSUE THREAD

**Issue by kopida** [kaitoy/pcap4j#229]
Dear Kaitoy,
I really appreciate your contribution on the solution to capture network packet.

I have tried the pcap4j. It is great. It can help to capture packets as TCP on an interface and process it to obtain the information carried by the packet. However, its operation is dependent on the pcap file. 

Can you please advice me is there any other way to process Inputstream of TCP packets and get the information inside those packet.

Many thanks for your advice.

Warm regards,
Chau

**Comment by kaitoy** [comment]
Thank you for using Pcap4J.

You can parse a byte array that's taken from the Inputstream by:

```java
PacketFactories.getFactory(Packet.class, DataLinkType.class)
        .newInstance(byteArray, 0, byteArray.length, DataLinkType.EN10MB);
```

**Comment by kopida** [comment]
Many thanks for your help and your contribution on the Pcap4J.
