### ISSUE TITLE
Any ways to get _ws.col.Info data

### ISSUE THREAD

**Issue by dikim33** [kaitoy/pcap4j#230]
Is there a way to get the **Info** data (_ws.col.Info) from a captured packet through pcap4j?

`tshark -r <pcap_file> -T fields -e _ws.col.Info`

On tshark, the **Info** data of each packet can be found but I am wondering if there is a way to extract such a data in pcap4j.

**Comment by kaitoy** [comment]
No.
_ws is data Wireshark adds. Pcap4J doesn't create it.
