### ISSUE TITLE
memory leak, LazyValues not being freed by readPacket* or loop

### ISSUE THREAD

**Issue by crowlogic** [kaitoy/pcap4j#232]
This bug was closed, even though it still exists, I think it should be re-opened 

https://github.com/kaitoy/pcap4j/issues/32

**Comment by kaitoy** [comment]
I monitored LazyValue with my sample program using VisualVM but couldn't reproduce the issue.

**Comment by crowlogic** [comment]
well, just because you cant reproduce it doesnt mean the bug isnt there, do the damn laws of physics and logic operate differently on my computer?

**Comment by kaitoy** [comment]
I can't investigate nor fix the issue without reproducing it.
Please provide a way (code) to reproduce.
