### ISSUE TITLE
How to get packets in real-time

### ISSUE THREAD

**Issue by nickyramone** [kaitoy/pcap4j#236]
I understand that using the native filters is more efficient than manually filtering in my code. Now, what happens if, with the filters I'm using, there are packets every 5 seconds but I need to react immediately as soon as they arrive?
In this scenario, given that I get 1 packet every 5 seconds, it will take a long time for the buffer to become full and send the packet to the library user (whether I use loop(), getNextPacketEx() or dispatch()).

Is there any solution or best practice for this?
Two approaches I can think of:
1) Reduce the buffer size to almost 0, but that doesn't seem like a good idea.
2) Reduce the timeout (for example, to 1 second), which is what I'm doing now.

Thank you.

**Comment by LucBerge** [comment]
I just tried -1 as timeout and it seams to work even though the javadoc says : "Must be non-negative". The javadoc is not clear on it.

**Comment by kaitoy** [comment]
According to the [manual of libpcap](https://www.tcpdump.org/manpages/pcap_open_live.3pcap.html), buffer timeout is expected to be a non-negative value.
But some platform might accept a negative value and it can be a solution for you.

**Comment by Icyrockton** [comment]
> I just tried -1 as timeout and it seams to work even though the javadoc says : "Must be non-negative". The javadoc is not clear on it.

really helpful .
and it help BPF filter work well too 😄
