### ISSUE TITLE
Automaticaly find the active PcapNetworkInterface

### ISSUE THREAD

**Issue by LucBerge** [kaitoy/pcap4j#239]
Is there a way to automaticaly find the active PcapNetworkInterface ? I can't find anything in the samples. If no, I would be happy to do it.

**Comment by kaitoy** [comment]
What do you mean "active" PcapNetworkInterface ?
There are any pcap handle opening on it, or it represents a  network device which is up, or something else?

**Comment by LucBerge** [comment]
Find the PcapNetworkInterface corresponding to the network device which is up, yes.

**Comment by kaitoy** [comment]
I think you can do like:

```java
var activePnifs = Pcaps.findAllDevs().stream()
  .filter((PcapNetworkInterface pnif) -> {
    return pnif.isUp();
  })
  .collect(Collectors.toList());
```

Note that PcapNetworkInterface#isUp() always returns false on some platforms.
For such platforms, Pcap4J doesn't provide a way to detect a network interface being up.

**Comment by LucBerge** [comment]
> Note that PcapNetworkInterface#isUp() always returns false on some platforms.
> For such platforms, Pcap4J doesn't provide a way to detect a network interface being up.

Which platform are you talking about ? I used to do an other method to find the up NetworkInterface. Could be interesting to see if it works.

**Comment by kaitoy** [comment]
I'm not sure which platforms are the case.
I've just ever seen comments saying so in libpcap manual, source code, or so.

Please try isUp() and see if it works.

**Comment by LucBerge** [comment]
Your solution is working fine.

I used to do like this (because I've never seen the isUp() method):
```
InetAddress currentAddress = null;
Enumeration<NetworkInterface> nis = NetworkInterface.getNetworkInterfaces();
while(nis.hasMoreElements() && currentAddress == null) {
	NetworkInterface ni = nis.nextElement();
	if(ni.isUp() && !ni.isLoopback()) {
		Enumeration<InetAddress> ias = ni.getInetAddresses();
		while (ias.hasMoreElements() && currentAddress == null)	{
			InetAddress ia = ias.nextElement();
			if(ia.isSiteLocalAddress() && !ia.isLoopbackAddress())
				currentAddress = ia;
		}
	}
}
if(currentAddress == null)
	throw new Exception("Make sure you have an internet connection.");
		
return Pcaps.getDevByAddress(currentAddress);
```

If someone has an issue on a specific platform, perhaps, you can try this.
