### ISSUE TITLE
how about compare to jnetpcap and dose it work in hybrid mode of the Network card

### ISSUE THREAD

**Issue by grubbyhou** [kaitoy/pcap4j#243]

**Comment by grubbyhou** [comment]
I also find the "setFilter" dose not work sometimes, but I don't find any reason.  Have you met the same problems? 
thank u!

**Comment by kaitoy** [comment]
What is hybrid mode?

**Comment by grubbyhou** [comment]
> What is hybrid mode?

Sorry,I mean 'PROMISCUOUS' and I found it out. But I cant solve the problem that dealing with the packet is more slow than getting the packet.

**Comment by kaitoy** [comment]
If you have some problems, create an issue for each one with the detail of the issue, your environment, and minimal code to reproduce the issue.
