### ISSUE TITLE
Sometimes can't catch any packages 

### ISSUE THREAD

**Issue by annpeter** [kaitoy/pcap4j#246]
i wirte follow code, sometimes it do catch packages, but sometimes it doesn't but i see wireshark 
do catch the packages at the same time.  especially when i have a breaking point at line 45, the following packages seem go nowhere.

![image](https://user-images.githubusercontent.com/7344217/71408091-f1540300-2677-11ea-9bfc-31c85e8ed617.png)

**Comment by kaitoy** [comment]
Please check your pcap filter.

https://www.tcpdump.org/manpages/pcap-filter.7.html

**Comment by annpeter** [comment]
@kaitoy  i removed all pcap filter，but it still sometimes work, sometimes bad.

**Comment by kaitoy** [comment]
I need more details or how to reproduce it for investigation.
