### ISSUE TITLE
Question about org.pcap4j.core.pcapLibName

### ISSUE THREAD

**Issue by dfshshw** [kaitoy/pcap4j#249]
How can i use org.pcap4j.core.pcapLibName in java program? i did not find which packet include this property. so could you tell me how to import it in my project? 

Besides, if there is not libpcap.so in OS, is it ok that i use ndk to cross-compile the libpcap.so and include it into my project?

Thank you very much.

**Comment by dfshshw** [comment]
ok, now i know that i should use java system property for the first question.

**Comment by kaitoy** [comment]
libpcap is not my library but a 3rd party's.
For questions about libpcap like your second one, please ask [libpcap project](https://www.tcpdump.org/).
