### ISSUE TITLE
Status code of a request

### ISSUE THREAD

**Issue by Taoode** [kaitoy/pcap4j#255]
Hi,kaitoy. thanks for your pacap4j. It work good for me. But how can I get the status code of a specific
request, I mean the response code such as 200,304.... Please give some advice,thanks!

**Comment by hyperxpro** [comment]
Do you mean HTTP response status code?

**Comment by Taoode** [comment]
> Do you mean HTTP response status code?

yeah

**Comment by hyperxpro** [comment]
You need to capture packets coming from TCP/80 and decode them using HTTP Decoder.

**Comment by hyperxpro** [comment]
Not sure if pcap4j has HTTP Decoder

**Comment by Taoode** [comment]
> Not sure if pcap4j has HTTP Decoder

Thanks hyperxpro, seems like pcap4j do not support HTTP capture , Now I just get the origin payload and transfer them, do you have some other alternative tools  to recommend which support HTTP capture packet primitively in Java?

**Comment by hyperxpro** [comment]
Not sure about any alternative but I can make HTTP Decoder on top of Pcap4j.

**Comment by Taoode** [comment]
> Not sure about any alternative but I can make HTTP Decoder on top of Pcap4j.

Cool! How you do it and you have a demo? That would be a great help for me,Thanks!

**Comment by eitzenbe** [comment]
you can recurse through the packets payloads until you get to the packet that contains the HTTP Response

```
Packet pp = packet.getPayload();
            int offset = 0;
            while (pp != null) {
                if (pp.getHeader() != null) {
                    offset += pp.getHeader().length();
                }
                pp = pp.getPayload();
            }
            byte[] by = packet.getPayload().getRawData();
            by = Arrays.copyOfRange(by, offset, by.length - offset);

            final String content = new String(by);
```

**Comment by Taoode** [comment]
@eitzenbe Thanks dude,that helps a lot!
