### ISSUE TITLE
我把抓到的数据包生成了pcap文件，但是不全，丢失很多

### ISSUE THREAD

**Issue by wuwanbao** [kaitoy/pcap4j#273]
发送一条带附件的邮件，开始捕捉包，生成pcap文件，数据丢失，无法还原附件，该怎么办？

**Comment by bdliang** [comment]
邮件的协议是smtp吧，是不是不支持？用户wireshark能抓么

**Comment by wuwanbao** [comment]
已经解决了，是因为winpcap的原因，我使用了npcap替换后数据正常了
