### ISSUE TITLE
IndexOutOfBounds in ByteArrays.calcChecksum

### ISSUE THREAD

**Issue by bkrahmer** [kaitoy/pcap4j#31]
I'm trying to port some code from C to java which is building packets.  I was having trouble getting the checksum for udp packets to match up, so after building the packet with the packet builder, I zeroed out bytes 26 and 27, then called short ck = ByteArrays.calcChecksum(retval);, which throws an exception.  It almost appears that it's expecting a packet to be a length of % 2, which I don't believe is a requirement.  I'm using 1.3.0.  Any ideas?  BTW, thanks for the awesome software.  If I make some money with my project, I will look into helping support the project.

java.lang.ArrayIndexOutOfBoundsException: arr.length: 53, offset: 52, len: 2
	at org.pcap4j.util.ByteArrays.validateBounds(ByteArrays.java:796) ~[pcap4j-core-1.3.0.jar:?]
	at org.pcap4j.util.ByteArrays.getShort(ByteArrays.java:125) ~[pcap4j-core-1.3.0.jar:?]
	at org.pcap4j.util.ByteArrays.getShort(ByteArrays.java:114) ~[pcap4j-core-1.3.0.jar:?]
	at org.pcap4j.util.ByteArrays.calcChecksum(ByteArrays.java:669) ~[pcap4j-core-1.3.0.jar:?]

**Comment by kaitoy** [comment]
The UDP RFC (https://www.ietf.org/rfc/rfc768.txt) says its checksum procedure is the same as is used in TCP.
And the TCP RFC (https://www.ietf.org/rfc/rfc793.txt) says as follows: "If a segment contains an odd number of header and text octets to be checksummed, the last octet is padded on the right with zeros to form a 16 bit word for checksum purposes."
So, we can expect a packet to be a length of % 2 when calculating UDP (and TCP) checksum.
Anyway, I fixed ByteArrays.calcChecksum() so it can process odd length data.
The fixed module is available on https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.3.1-SNAPSHOT/pcap4j-distribution-1.3.1-20150212.203517-3-bin.zip

**Comment by bkrahmer** [comment]
awesome! thanks so much.  i will test it out.  i don't have a ton of confidence in the code i'm porting, but i wasn't sure.  cheers

**Comment by bkrahmer** [comment]
So after correctly building a psuedo-header and combining it with the udp data, i now have correct checksums with the 1.3.1 snapshot.  Went back to 1.3.0, and the exception came back.  So I can confirm this was a bug, and that it is now fixed.  Thanks!  I will look forward to a 1.3.1 release so maven is happy again :)

**Comment by bkrahmer** [comment]
So I ran into another issue.  My icmp packets with an odd number of data bytes are getting a different checksum value than my reference data.  My reference function is here: http://www.openvas.org/src-doc/openvas-libraries/nasl__packet__forgery_8c.html#a362b3b18702149ba9369675c6b09a4e7
For this data: { 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe9, 0x36, 0xee, 0x50, 0xf1, 0xdd, 0x2a, 0xcc, 0x6e } libnasl says 9dcd while pcap4j says 0b60.  I think that perhaps instead of sum += 0xFFL & data[data.length - 1] it should be  sum += 0xFFFFL & (data[data.length - 1] << 8), which seems to work, but I don't know if there are additional considerations.  Thanks

**Comment by kaitoy** [comment]
The data used to calculate ICMP checksum never be odd as well as UDP. See https://tools.ietf.org/html/rfc792. I don't see any problems in  ByteArrays.calcChecksum() itself.

**Comment by bkrahmer** [comment]
Sorry, but I think you are wrong here.  Checksums for icmp and udp start with the header (or psuedo-header), and continue through the data.  The data is allowed to be an odd number of bytes, so as the RFCs mention, if that is the case, an extra 0 byte is added.  If I take the test data mentioned above and add an extra 0 byte and call your 1.3.0 function, I get the correct checksum of 0x9dcd.  This is the same effect as << 8 on a lone end byte, not just adding it as is.  You are in effect adding 0x006e instead of 0x6e00.  thanks.

**Comment by kaitoy** [comment]
ByteArrays.calcChecksum() is a general utility method the use of which is not limited to UDP and ICMP. Its an implementation of RFC 1071. Adding 0 when odd is a specific rule of UDP, TCP, and ICMP (and maybe some other protocols), not a general rule for checksum calculation. I don't want to implement such specific rule into ByteArrays.calcChecksum(). When you calculate a checksum from an odd ICMP data, please append 0 to the data before calling ByteArrays.calcChecksum().

**Comment by bkrahmer** [comment]
I think you should read this post and re-consider your stance.  Your implementation is incorrect.  http://stackoverflow.com/questions/14080875/does-the-c-code-algorithm-in-rfc1071-work-well-on-big-endian-machine  (wireshark source here: https://github.com/boundary/wireshark/blob/master/epan/in_cksum.c)  You are in fact saying that your implementation is more correct than wireshark or tcpdump on OS X...
You say that it's a general utility method, but that doesn't change the fact that it is giving incorrect results in its primary usage.  It's silly to create a whole new buffer in 1/2 the cases just to work around this bug.  I can't just append a byte, because that would change the data

**Comment by kaitoy** [comment]
Eventually I got it. I haven't noticed RFC 1071 has the erratum. Thank you for pointing it. I fixed the calcChecksum(). Please try https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.3.1-SNAPSHOT/pcap4j-distribution-1.3.1-20150216.090531-5-bin.zip.

**Comment by bkrahmer** [comment]
Bingo!  thanks again.

**Comment by kaitoy** [comment]
1.4.0 has been released with the fix.
