### ISSUE TITLE
LinuxSllPacket not correctly managed by handle.getNextPacket() on offline pcap

### ISSUE THREAD

**Issue by UnToxxx** [kaitoy/pcap4j#34]
Hello,

I try to parse a saved pcap file of a PPP capture made on Linux, leading to a LinuxSllPacket.
In logs getNextPacket() seems to well identify the packet type : 
- [org/pcap4j/packet/factory/packet-factory.properties] Got org.pcap4j.packet.LinuxSllPacket by org.pcap4j.packet.Packet.classFor.org.pcap4j.packet.namednumber.DataLinkType.113

 I checked in the mapping properties file, it is the right one : 
org.pcap4j.packet.Packet.classFor.org.pcap4j.packet.namednumber.DataLinkType.113 = org.pcap4j.packet.LinuxSllPacket

The handle's DataLayerType retrieved is the right one : 
--> 113 (Linux cooked-mode capture)

but the packet type returned is an IllegalPacket :
Packet class org.pcap4j.packet.IllegalPacket

I use the 1.4.0 version of the library.

Here is Wireshark extract for the pcap file :
![image](https://cloud.githubusercontent.com/assets/4004519/7067307/7e829ba6-deca-11e4-89ed-96ac22ad815d.png)

Could you help me ?

Thanks,
Alexandre

**Comment by kaitoy** [comment]
I found the cause, where LinuxSllPacket doesn't accept zero length address. I will fix it.

**Comment by kaitoy** [comment]
I made the fix. Please try https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.4.1-SNAPSHOT/pcap4j-distribution-1.4.1-20150412.065114-1-bin.zip.

**Comment by UnToxxx** [comment]
Hello,

the issue is correctly fixed in the new version 1.4.1. Thank you very much for your replies and the fix.

Regards,
Alexandre
