### ISSUE TITLE
Support to change buffer size when opening live capture

### ISSUE THREAD

**Issue by postol** [kaitoy/pcap4j#38]
Hi,

we are using openLive method to get a handler and start the loop on it. We want to change the buffer size, but there is no API exposed for such functionality. Do you think you can provide the API to do so? We checked the code and it is only used inside of PcapHandler builder class.

Thank you and kind regards,

Petr

**Comment by kaitoy** [comment]
Pcap4J already supports changing buffer size using PcapHandle.Builder. Please refer to a sample https://github.com/kaitoy/pcap4j/blob/master/pcap4j-sample/src/main/java/org/pcap4j/sample/GetNextPacket.java for the usage.
