### ISSUE TITLE
Support to open live capture on iface without IP address

### ISSUE THREAD

**Issue by postol** [kaitoy/pcap4j#39]
Hi,

it would be nice to add an option to open live capture on interface, which doesn't have any IP address assigned. Use case - on Solaris you can set up IPMP group to which you assign IP address. Such group has two underlying interfaces which doesn't have IP address assigned, but you want to capture on one of the underlying interface. We tried tcpdump and it supports it ... you can do tcpdump -I <underlying iface> and it works.

We have checked the code and the problem is that findAllDevs method doesn't return such an interface and therefore with current API you can't open live capture on it. But if you call NativeMappings.pcap_open_live(deviceName, ...) the capturing works.

So maybe a static method on PcapNetworkInterface class

public static PcapHandle openLive(String deviceName, int snaplen, PromiscuousMode mode, int timeoutMillis)

which will allow to specify the deviceName directly would be useful.

Thank you and kind regards,

Petr

**Comment by kaitoy** [comment]
Thank you for the interesting use case. I'd never thought such a case.
Anyway, with current version of Pcap4J, you can open a PcapHandle by a deviceName using PcapHandle.Builder.
Please refer to a sample https://github.com/kaitoy/pcap4j/blob/master/pcap4j-sample/src/main/java/org/pcap4j/sample/GetNextPacket.java for the usage.
