### ISSUE TITLE
Using pcap4j without root privileges

### ISSUE THREAD

**Issue by bruskli** [kaitoy/pcap4j#40]
It is not clearly stated on the great documentation of your package, but you can
add caps to the java binary in order to make live captures without being root. 

setcap cap_net_raw,cap_net_admin=eip $JAVA_BIN
java = cap_net_admin,cap_net_raw+eip

More info here
http://packetlife.net/blog/2010/mar/19/sniffing-wireshark-non-root-user/

**Comment by kaitoy** [comment]
Thank you for the information.
I've ever tried it when [issue22](https://github.com/kaitoy/pcap4j/issues/22), but I've not documented at that time.
I added description about Linux capabilities to READMEs.
