### ISSUE TITLE
Add benchmark testing

### ISSUE THREAD

**Issue by yogevyuval** [kaitoy/pcap4j#41]
The library should be checked in terms of performance and should compare itself to other popular alternatives

**Comment by kaitoy** [comment]
You're right. It must be better. But I really don't have enough resource (both environment and manpower) to do it now...

**Comment by kaitoy** [comment]
No plan...

**Comment by otisg** [comment]
Btw. would it be possibly to borrow anything from https://bitbucket.org/robeden/pcap4j-optimized to improve performance?

**Comment by kaitoy** [comment]
I don't think so.

I know the project. It's optimization is to remove packet dissection and focus on packet capturing.
At the time pcap4j-optimized was forked, Pcap4J didn't support such feature but now does by raw API (e.g. [PcapHandle#getNextRawPacket()](https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-core/src/main/java/org/pcap4j/core/PcapHandle.java#L656)).

And, after pcap4j-optimized was forked, I made some performance improvement in [the native mappings](https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-core/src/main/java/org/pcap4j/core/NativeMappings.java), so I think current Pcap4J can work faster than pcap4j-optimized.
