### ISSUE TITLE
IPv6 packets can be dumped to file incorrectly

### ISSUE THREAD

**Issue by jpanczyk** [kaitoy/pcap4j#42]
An IPv6 packet with a high (>127) traffic class will not be properly written to a pcap file. Since traffic class is a byte, values higher than 127 are actually negative, and corrupt the version nibble (all bits are high) when raw data is created through bitwise or'ing.

The method `getRawFields()`:

```java
rawFields.add(
    ByteArrays.toByteArray(
        version.value() << 28 | trafficClass.value() << 20 | flowLabel.value()
    )
);
```

Bit masking of trafficClass.value() with 0xFF before the shift should fix the problem.

**Comment by kaitoy** [comment]
Thank you for pointing it.
You are right. I fixed it.
