### ISSUE TITLE
Create new PCAP file

### ISSUE THREAD

**Issue by TribuneX** [kaitoy/pcap4j#43]
Hello,

this is more a question than an issue.
Is there a way to create a pcap file from sketch, without having to load an existing file first?
In order to initiate a PcapDumper object, I am currently doing this:
PcapHandle handleRead = Pcaps.openOffline(filePath);
PcapDumper dumper = handleRead.dumpOpen(filePath);

But it seems odd to first open a file offline, just to overwrite it in the second call. Did I miss something in the handleRead class?
Thanks for helping! 

Kind regards, 
Sascha

**Comment by kaitoy** [comment]
To create a PcapDumper object, a PcapHandle object is necessary. But you don't need to do openOffline. The most common way to create a PcapDumper object is as follows:
```java    
PcapHandle h = Pcaps.openDead(DataLinkType.EN10MB, 65536);
PcapDumper dumper = h.dumpOpen("/path/to/pcapfile");
```

**Comment by TribuneX** [comment]
Thanks for that hint! Works as expected.

**Comment by kaitoy** [comment]
Thank you for using Pcap4J.
Let me close this.
