### ISSUE TITLE
please create a new release

### ISSUE THREAD

**Issue by divaykin** [kaitoy/pcap4j#44]
Dear @kaitoy could you please create a new release - I need to have nano precision, would be great to have it on mavencentral, etc. Thx

**Comment by kaitoy** [comment]
Sure. I will, soon.
I'm afraid the nano precision methods are not yet well tested and problems may be found.
I will release a minor minor version in that case.

**Comment by kaitoy** [comment]
Pcap4J 1.6.0 has been released.
