### ISSUE TITLE
Wi-Fi packet dissection

### ISSUE THREAD

**Issue by Inlustra** [kaitoy/pcap4j#45]
Hi,
This is really as much of a question as it is an enhancement. I'd love to use the library and have it actively sniffing "probe requests" using the Bpf: "subtype probereq". Unfortunately it seems Pcap4j is unable to parse these packets as well as the DataLinkType 127 or DLT_IEEE802_11_RADIO information.

I would like to use the DLT to get the RSSI (Signal Strength) of the packet. Is there any documentation on how to manually add a new link type along with information? is this even supported? 

I could add an AbstractPacket for dissecting the Probe Request but, unfortunately it wouldn't be worth it without the DLT information. 

Thanks.
Tom

http://www.tcpdump.org/linktypes.html

**Comment by kaitoy** [comment]
Which packet factory module are you using? If properties-based packet factory, setting the system property `org.pcap4j.packet.Packet.classFor.org.pcap4j.packet.namednumber.DataLinkType.127 = org.pcap4j.packet.YourPacketClass` may solve the problem.
If I am misunderstanding the problem, please let me know.
