### ISSUE TITLE
Add original length to packet

### ISSUE THREAD

**Issue by hintzed** [kaitoy/pcap4j#48]
First of all, after trying two other Java pcap libraries and trying to write a simple one myself, I very much appreciate your work!

For a research project I need to parse pcap files, split them by package, store them in some custom format and later write them back in pcap format. That works fine with pcap4j, except that apparently it lacks the information of the original packet length (at the moment packets apparently only include the captured length, which might be less).  

Implementing it is fairly easy (adding it to NativeMappings pcap_pkthdr), hence I did so in order to solve my problem. However, I would very much appreciate it becoming a feature of the official library, so I would not need to manage a fork. I could provide a pull request if you chose to implement this feature, though I am unsure about how to "correctly" place it within the structure for pcap4j. My solution at the moment is rather hacky.

**Comment by kaitoy** [comment]
Thank you for using Pcap4J!
I will implement the feature soon.

**Comment by kaitoy** [comment]
I added `PcapHandle.getOriginalLength()` which you can use in the same manner as `PcapHandle.getTimestamp()`.
If you want to try it please download [the snapshot build](https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.6.2-SNAPSHOT/pcap4j-distribution-1.6.2-20151205.155517-2-bin.zip).
