### ISSUE TITLE
Unable to get MAC address of PcapNetworkInterface on windows

### ISSUE THREAD

**Issue by maffoo** [kaitoy/pcap4j#49]
I'd like to be able to find the MAC address of a `PcapNetworkInterface` on windows, but `getLinkLayerAddresses` returns an empty array. Is there any way to make this work, maybe by configuring something in the os, or winpcap, or pcap4j?

I _am_ able to find MAC addresses using the `java.net.NetworkInterface` class, however the list of network interfaces enumerated by that class does not line up with what is given by `Pcaps.findAllDevs()`, so there's no reliable way I can see to get the right MAC address with the right pcap network interface (both the name and description fields are different in the two classes).

Any thoughts about how to reliably get MAC addresses for pcap devices on windows?

**Comment by kaitoy** [comment]
I will try to enhance Pcap4J to retrieve MAC addresses on Windows.

**Comment by kaitoy** [comment]
I implemented it.
Please download the [snapshot build](https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.6.2-SNAPSHOT/pcap4j-distribution-1.6.2-20151206.172239-3-bin.zip) if you want to try it.

**Comment by maffoo** [comment]
Confirmed that this works for us on windows. Thanks for the quick fix! When do you plan to release 1.6.2?

**Comment by kaitoy** [comment]
I will release it soon, this weekend or next week.

**Comment by kaitoy** [comment]
It's been released!
