### ISSUE TITLE
Can I run filter on PcapHandle created from Pcaps.openOffiline()?

### ISSUE THREAD

**Issue by tenaciousjzh** [kaitoy/pcap4j#51]
Hello,
I'm working on a project where we've got pcap files that were created before my code gets called. Some of these pcap files can get fairly large (5-10GB). Is pcap4j able to support the scenario where my code would the pcap file offline and then call setFilter() so that I can create a much smaller dump file with only the packets that match the filter?

In my attempts to do this so for, the PcapHandle let's me set the filter but when I call getNextPacketEx() on the handle, it returns an EOFException.

Thanks for your time and consideration!

**Comment by kaitoy** [comment]
Yes, you can do it as like below:

```java
PcapHandle ph = Pcaps.openOffline("C:\\Users\\Kaito\\Desktop\\test.pcap");
ph.setFilter("tcp", BpfProgram.BpfCompileMode.OPTIMIZE);
while (true) {
  try {
    Packet p = ph.getNextPacketEx();
    if (p != null) {
      System.out.println(p);
      // code to dump the packet to a file.
    }
  } catch (EOFException e) {
    System.out.println("End of pcap file");
    break;
  } catch (TimeoutException e) {
    System.out.println("TimeoutException");
  }
}
```

EOFException means Pcap4J reached the end of the pcap file.
If you saw the exception before you got any packets, please re-check your filter expression referring to [here](http://biot.com/capstats/bpf.html).

**Comment by mon205** [comment]
This seems an old topic, but I think the answer is incorrect, and the filters mentioned in the comment and the link provided are related to the live traffic not the offline traffic from a file.
The simple filter in the example which is "tcp" didn't bring back any packet in pcap4j 2.0.0
