### ISSUE TITLE
Method javadoc misleading for return type, Packet.getPayload() line 36.

### ISSUE THREAD

**Issue by smqureshi** [kaitoy/pcap4j#54]
Last line should be 'May be null if the payload doesn't exist' instead of 'May be null if the payload exist'
/**
   * Returns the Packet object representing this packet's payload.
   *
   * @return the Packet object representing this packet's payload.
   *         May be null if the payload exist
   */

**Comment by CBrowne** [comment]
https://github.com/kaitoy/pcap4j/pull/55

**Comment by smqureshi** [comment]
That's fine now, thanks @CBrowne

**Comment by kaitoy** [comment]
Thank you for pointing it out to me, @smqureshi .
And thank you for the fix @CBrowne . I merged it.
