### ISSUE TITLE
Packet direction capture support

### ISSUE THREAD

**Issue by zahidMed** [kaitoy/pcap4j#61]
openlive argument that allows specifying the capture direction: incoming packet, outgoing packets or both. like openlive100 of jnetPcap.
thanks.

**Comment by kaitoy** [comment]
Done. I will release 1.6.4 with the support soon.

**Comment by zahidMed** [comment]
Sorry, I was so busy that I didn't pay attention to the native method name. I'am waiting for this release in maven repo.

**Comment by nonokatori** [comment]
Hello! I'm sorry. Can you help me? 
When I tried to use this method in OS Windows I get this:
```
Exception in thread "main" org.pcap4j.core.PcapNativeException: Failed to set direction: Setting direction is not implemented on this platform
	at org.pcap4j.core.PcapHandle.setDirection(PcapHandle.java:268)
	at Main.main(Main.java:56)
```

Why? Is this only for Unix-system?

**Comment by zahidMed** [comment]
I think it's a limitation in Windows OS (same for Solaris 10) but @kaitoy can confirms this.
