### ISSUE TITLE
When I set the setcap cap_net_raw,cap_net_admin=eip /path/to/java; the java can not run anymore, it report the error below

### ISSUE THREAD

**Issue by xiaoleihuang** [kaitoy/pcap4j#63]
Initially, I would like to run java -cp pcap4j-core.jar:pcap4j-packetfactory-static.jar:pcap4j-sample.jar:jna-3.5.2.jar:slf4j-api-1.6.4.jar org.pcap4j.sample.SendArpRequest 192.168.209.1;
It required to choose with the following instruction:
 NIF[0]: enp9s0
      : link layer address:  
      : address: / 
      : address: / 
      : address: / 
NIF[1]: any
      : description: Pseudo-device that captures on all interfaces
NIF[2]: lo
      : link layer address: 00:00:00:00:00:00
      : address: /127.0.0.1
      : address: /0:0:0:0:0:0:0:1
NIF[3]: wlp3s0
      : link layer address:  
NIF[4]: docker0
      : link layer address:  
      : address: / 

****Some exception prompted after choosing the first device.**** 

However, it said I did not have permission withe the exception below:
Exception in thread "main" org.pcap4j.core.PcapNativeException: enp9s0: You don't have permission to capture on that device (socket: Operation not permitted)
	at org.pcap4j.core.PcapNetworkInterface.openLive(PcapNetworkInterface.java:258)
	at org.pcap4j.sample.SendArpRequest.main(SendArpRequest.java:74)

So I set the setcap cap_net_raw,cap_net_admin=eip /path/to/java in my Ubuntu. Then the java can not run anymore, it report the error below:
java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory

How to fix it?

**Comment by kaitoy** [comment]
It's probably the same issue as [this](http://unix.stackexchange.com/questions/16656/problem-to-launch-java-at-debian-error-while-loading-shared-libraries-libjli).
Setting LD_LIBRARY_PATH to include where libjli.so is may solve the issue.

**Comment by xiaoleihuang** [comment]
I tried this method to set libjli.so in the PATH, but it did not work either. I tried following in either /etc/profile or ~/.bashrc:
\# libjli.so path
export PATH=/usr/local/java/jre/lib/amd64/jli/libjli.so:$PATH

Later, I tried:
\# libjli.so path
export PATH=/usr/local/java/jre/lib/amd64/jli:$PATH

They did not work at all. Then I tried root, 
under root account, java -v does not work, but java -version does work....

**Comment by kaitoy** [comment]
How was LD_LIBRARY_PATH? Did you try it?

**Comment by xiaoleihuang** [comment]
Yeah, I just tried it with the following code in either /etc/profile or ~/.bashrc:
export LD_LIBRARY_PATH=/usr/local/java/jre/lib/amd64/jli
export PATH=${LD_LIBRARY_PATH}:$PATH
\#export PATH=/usr/local/java/jre/lib/amd64/jli/libjli.so:$PATH

It did not work. T-T, sad Saturday afternoon.

**Comment by kaitoy** [comment]
Try `ln -s /usr/local/java/jre/lib/amd64/jli/libjli.so /usr/lib/`.
Or `echo /usr/local/java/jre/lib/amd64/jli/ >> /etc/ld.so.conf`

**Comment by xiaoleihuang** [comment]
Thank you. The first command works! I appreciate your help.

I have not tried the second command. 
BTW, I am curious why the both commands would work. 
Why making such soft link could solve the problem? Does that mean to add the file to lib path?

**Comment by kaitoy** [comment]
You are right.
The error occurred because java couldn't find a shared library, libjli.so. The reason why the java lost sight of it after setting setcap cap_net_raw,cap_net_admin=eip is explained at the link I indicated above.
All of my suggestions intended to let the java know the place of libjli.so. Generally speaking, shared libraries are searched in specific directories. `LD_LIBRARY_PATH` and `/etc/ld.so.conf` are to specify the directories. `ln -s /usr/local/java/jre/lib/amd64/jli/libjli.so /usr/lib/` is another approach that adds libjli.so to the directory (i.e. /usr/lib/) which is searched by default.

**Comment by xiaoleihuang** [comment]
Thank you. BTW, pcap packet seems to contains no timestamp, instead, I have
to use handler.gettimestamp method to retrieve the time. Will this cause
any time errors? Is there a method to retrieve packets that contain
timestamp inside of them?

**Comment by kaitoy** [comment]
No, PcapHandler#getTimestamp() returns a correct timestamp.

**Comment by yarbshk** [comment]
Unfortunately this solution isn't working:
> Or `echo /usr/local/java/jre/lib/amd64/jli/ >> /etc/ld.so.conf`

...however this one works like a charm:
`echo /usr/local/java/jre/lib/amd64/jli/ >> /etc/ld.so.conf.d/java.conf`

\* the name of file (in this case `java.conf`) could be whichever but it's necessary to ends with `.conf`

**Comment by bjwktcsnzh** [comment]
@xiaoleihuang 

[This blog](https://www.cnblogs.com/chenxueqiang/p/13653623.html) explains the reason .
