### ISSUE TITLE
Pcaps.findAllDevs() Returns Bluetooth Interface Only

### ISSUE THREAD

**Issue by saden1** [kaitoy/pcap4j#66]
I am using libpcap 1.5.3 with  Java 8 on Mint Linux 17.3 64bit system. When I call Pcaps.findAllDevs() I get back bluetooth0 interface only. Any idea what is going on?

**Comment by kaitoy** [comment]
I built the same environment but I could find all devices and capture packets normally.
Please install wireshark and see if it can find all devices. If it cannot pcap4j cannot.

**Comment by saden1** [comment]
Hi @kaitoy, thanks for the quick response. I installed wireshark as you suggested and was not able to see all the devices. Did you run your test using a user with a specific linux group that has specific privileges? 

If there are extra things I need to do I would love to know and see it documented.

**Comment by kaitoy** [comment]
I think I tested with root. Pcap4J (and Wireshark) needs some specific capabilities.
Please refer to [here](https://github.com/kaitoy/pcap4j#others).
