### ISSUE TITLE
Obtaining timestamps for packets read from pcap file

### ISSUE THREAD

**Issue by sandhu** [kaitoy/pcap4j#68]
I have a dump of previously captured `pcap` files that I am attempting to analyze with this library. Following the example provided at https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-sample/src/main/java/org/pcap4j/sample/ReadPacketFile.java, I have no issue reading and dissecting the packets, however I am unable to get the original capture timestamp for the packet.

Using `getTimestamp` on the handle object returns a NULL.

Thank you for the excellent work on this library.

**Comment by kaitoy** [comment]
Thank you for your interest in Pcap4J.

Probably you attempted `getTimestamp` in a different thread from one you captured a packet from the pcap file, right? The `getTimestamp` returns the timestamp of the last packet captured by the pcap handle in the current thread.

**Comment by sandhu** [comment]
I did it in the same thread right after calling `getNextPacketEx`

**Comment by sandhu** [comment]
I'm working in clojure, but can produce a minimal sample if needed.

**Comment by kaitoy** [comment]
Could you provide me the sample?

**Comment by sandhu** [comment]
My sincere apologies. 

When putting together the minimal sample with your `echoAndEchoReply.pcap` file, everything works as expected.

I'll debug further to see why things are broken with my larger application.

**Comment by xuezhaojun** [comment]
How can I capture a 802.11 packet and parse it? is 802.11 supported？

**Comment by kaitoy** [comment]
Only Probe Request is supported for now.
