### ISSUE TITLE
PcapNetworkInterface open live with NONPROMISCUOUS mode

### ISSUE THREAD

**Issue by liadga** [kaitoy/pcap4j#71]
I use pcap4j version 1.65 and I try to open the network interface for listening in NONPROMISCUOUS mode.
My code looks like this:
pcapHandle = pcapNetworkInterface.openLive(Short.MAX_VALUE, PcapNetworkInterface.PromiscuousMode.NONPROMISCUOUS,3000);

Although I open it in non promiscuous mode it seems that I receive TCP packets which are not intended for my network interface.

I am not sure if it is important or not but I use VBOX with windows 2008 R2 and the network card is configured to enable promiscuous mode  

Any Idea what am I doing wrong?

**Comment by liadga** [comment]
Never mind after reading some more found that non-promiscuous may sometime be promiscuous 
More info can be found here: http://www.tcpdump.org/pcap.html - "promisc, when set to true, brings the interface into promiscuous mode (however, even if it is set to false, it is possible under specific cases for the interface to be in promiscuous mode, anyway"

**Comment by kaitoy** [comment]
Promiscuous mode is often not very trustworthy.
Instead, you can trust a filter like `pcapHandle.setFilter("tcp and host 192.168.1.100", BpfCompileMode.OPTIMIZE);`
