### ISSUE TITLE
How to get source and destination ports?

### ISSUE THREAD

**Issue by spyhunter99** [kaitoy/pcap4j#72]
Not really a problem per say, but I'm poking around in the IpV4Header class and can't find any references source or destination ports. Am I missing something or is this information located elsewhere? It's rather critical to be able to match ports to protocols

**Comment by kaitoy** [comment]
Ports are in [TcpHeader](https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-core/src/main/java/org/pcap4j/packet/TcpPacket.java#L483) or [UdpHeader](https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-core/src/main/java/org/pcap4j/packet/UdpPacket.java#L320).
