### ISSUE TITLE
I think 'npcap' much better for Windows instead of 'winpcap'

### ISSUE THREAD

**Issue by ZetaoYang** [kaitoy/pcap4j#79]
Npcap is here: https://github.com/nmap/npcap.
I hope pcap4j can support npcap.

**Comment by kaitoy** [comment]
I've ever done some tests on [Pcap4J with Npcap](https://tbd.kaitoy.xyz/2016/01/12/pcap4j-with-four-native-libraries-on-windows10/#npcap).
At that time, I installed Npcap with `WinPcap Compatible Mode` on and confirmed Pcap4J can work well over it.
I will add note about Npcap to the readme.

**Comment by ZetaoYang** [comment]
That's great. 
Thank you.
