### ISSUE TITLE
Intermittent SIGSEGV in finalizer for BpfProgram

### ISSUE THREAD

**Issue by lampad** [kaitoy/pcap4j#80]
I'm writing a JRuby wrapper for pcap4j (thanks for all your hard work): https://github.com/lampad/pcap4JRuby using jruby-9.1.6.0, and have been running into an intermittent segfault when i run my unit test suite `bundle exec rake` a few times. I've been working on getting a more streamlined, reproducible segfault test, and will update later when I have something.

I noticed that this was committed a while ago: https://github.com/kaitoy/pcap4j/commit/36a5b432a2789b42e38999737131c74d6125bfc6

I had been having the same problem that was described in https://github.com/kaitoy/pcap4j/issues/64, and after that commit, the mention of JNA in the stack disappeared. However, I'm still getting the segfault and it appears to be caused by the freeing of the BpfProgram in `org.pcap4j.core.NativeMappings.pcap_freecode` I suspect a double free, since the memory address seems to point to a null address (one that has already been freed?)

I've attached the log below.
[hs_err_pid9247.txt](https://github.com/kaitoy/pcap4j/files/655779/hs_err_pid9247.txt)

Let me know if you have any questions.

**Comment by kaitoy** [comment]
It looks the error can be avoided by checking the `freed` flag in `free()`.
I made the fix. Please try this: https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.7.1-SNAPSHOT/pcap4j-distribution-1.7.1-20161215.220212-3-bin.zip

And, now I believe implementing finalize method is [problematic](https://www.securecoding.cert.org/confluence/display/java/MET12-J.+Do+not+use+finalizers). So I will remove it in Pcap4J 2.0.0

**Comment by lampad** [comment]
Looks like that addressed it. Thanks for the quick turnaround.
