### ISSUE TITLE
Problem with PCAP non-root

### ISSUE THREAD

**Issue by Stevod** [kaitoy/pcap4j#82]
I have done the setcap on the java file, but still I get the error message: Exception in thread "main" org.pcap4j.core.PcapNativeException: enp0s3: You don't have permission to capture on that device (socket: Operation not permitted)

Any idea why? I am running on Ubuntu 16.10.

Here's the getcap output:
>getcap /usr/lib/jvm/java-8-oracle/jre/bin/java
>/usr/lib/jvm/java-8-oracle/jre/bin/java = cap_net_admin,cap_net_raw+eip

and here's the executable linked from /usr/bin/java using update-alternatives
There is 1 choice for the alternative java (providing /usr/bin/java).

     ------------------------------------------------------------
   0            /usr/lib/jvm/java-8-oracle/jre/bin/java   1081      auto mode
* 1            /usr/lib/jvm/java-8-oracle/jre/bin/java   1081      manual mode

Interestingly, I also get the same error message when I set the interface to non-promiscuous as follows:

final PcapHandle handle
      = nif.openLive(SNAPLEN, PromiscuousMode.NONPROMISCUOUS, READ_TIMEOUT);

Why would that be?

**Comment by kaitoy** [comment]
I'm investigating now.

**Comment by kaitoy** [comment]
I can run Pcap4J by non-root with the capabilities on Ubuntu 13.04. (I don't have 16.10.)
Is [this](http://stackoverflow.com/questions/29099797/raw-capture-capabilities-cap-net-raw-cap-net-admin-not-working-outside-usr-b) your case?

**Comment by kaitoy** [comment]
ping

**Comment by Stevod** [comment]
Hi kaito,
Sorry for the delay in responding.

The issue you mention may well be the problem, but after I posted my issue, I have been digging around and concluded that my particular use may be better suited to wrapping the whole of command-line tcpdump and calling that from java, rather than using a full java library for decodes. Therefore, I'm not going to investigate using pcap4j further on Ubuntu 16.10, unless the tcpdump approach turns out not to work. If that happens, I'll certainly look again at pcap4j.

Thanks for your efforts on developing this piece of software though.

Stevod

**Comment by kaitoy** [comment]
That's ok.
Please just remember Pcap4J can parse packets stored in pcap files generated by tcpdump.
