### ISSUE TITLE
How to block internet

### ISSUE THREAD

**Issue by vinodatphp** [kaitoy/pcap4j#83]
How do I block internet and check captured packets to block or access internet like firewall, I need some code snippet

**Comment by kaitoy** [comment]
Can you explain your system structure?

**Comment by vinodatphp** [comment]
My project is malware traffic detection system, want to block malicious traffic. It an college project.

**Comment by kaitoy** [comment]
Pcap4J can't block any traffic, but only can sniff it.
If you run a Pcap4J app on a server which stays between the PC with malware and the internet, the app can work just like firewall. But this is not what you want, right?

**Comment by kaitoy** [comment]
ping
