### ISSUE TITLE
Memory leak in PacketFactoryPropertiesLoader cache

### ISSUE THREAD

**Issue by julian-klode** [kaitoy/pcap4j#86]
PacketFactoryPropertiesLoader.java maintains a cache of properties. The cache has no upper bound,  though, causing a continous increase in memory usage when building packages. 

This caused a memory leak in julian-klode/dns66 - dns66 is an android app to filter hostnames at the DNS level, and runs for long times. I added an ugly work around for this to clear the cache via reflection in https://github.com/julian-klode/dns66/commit/654c901f71de0a1faf70e0e150baeae5ffd13366 but this is somewhat suboptimal.

Running DNS66 and `while true; do busybox nslookup example.com ; done  > /dev/null` on the adb shell, the memory usage of the app increases within ten minutes. By flushing the cache every 1024 requests (which is probably every ~300 packets build), memory usage stays constant.

Switching to the static factory also works on my machine, but I can't get DNS66 to build with that on travis: `Multiple dex files define Lorg/pcap4j/packet/factory/StaticUnknownPacketFactory`.

So, what I'd recommend is adding a reasonable size limit for the cache and then flushing out entries; either all entries, or just the eldest one (as you can easily do with `LinkedHashMap`).

**Comment by kaitoy** [comment]
Could you provide me the log?

**Comment by julian-klode** [comment]
Well, I just dumped memory every few minutes and noticed the entry count in the hashmap used by the cache to increase. And well, overall memory increased. After adding the work around, memory usage remained basically constant.

I could try to build a log file by writing some reflection code to access the cache's map and just dump it to a file every 1024 calls or so, but that's probably painful.

**Comment by julian-klode** [comment]
Or well, maybe I can somehow produce an hprof dump file at the end that you could read, or run some analyser on it or something?

**Comment by kaitoy** [comment]
Oh, I just meant PacketFactoryPropertiesLoader's logs. Pcap4J uses [SLF4J](https://www.slf4j.org/manual.html), so, for example, adding slf4j-simple.jar to your classpath shows the logs in the console.

**Comment by julian-klode** [comment]
Ah. Hmm, I'll see if I can figure that out :)

**Comment by julian-klode** [comment]
See https://gist.github.com/61eeaa5ccbad9b0a706f8e1db2a3bc80 - It's always

Could not get value by org.pcap4j.packet.Packet.classFor.org.pcap4j.packet.namednumber.UdpPort.47018, use default value: class org.pcap4j.packet.UnknownPacket

well, with different port numbers. See

**Comment by julian-klode** [comment]
It is not really a leak per se, it just caches up the 2**16 elements port numbers (34k HashMapEntry take about 7 MB, plus about 4-5MB for the keys, plus about 3MB for the list of entries in the map, so about 15MB for 34, so a bit less than 30 MB for 65k). This estimation (from the heap profile) might miss a few things, so real life memory usage might be higher.

I'm not sure if caching 2**16 entries (and more, if I had TCP packets) really is a good thing. 30MB seems like a lot of memory. But oh well, I guess I'd be happy with static packet factory if #88 gets fixed :) [not sure what the disadvantage is, both seem to work fine in non-release builds].

**Comment by kaitoy** [comment]
So, I close this issue without modifying the properties-based packet factory. You will be able to use the static factory instead.
The static factory doesn't have any cons other than you can't change packet class mappings without modifying the source, which the properties based factory can.
