### ISSUE TITLE
pcap4-core and pcap4j-packetfactory-static both ship org.pcap4j.packet.factory.StaticUnknownPacketFactory

### ISSUE THREAD

**Issue by julian-klode** [kaitoy/pcap4j#88]
pcap4-core and pcap4j-packetfactory-static both ship org.pcap4j.packet.factory.StaticUnknownPacketFactory, this in turns breaks building with the static packet factory for Android, as it complains about the class being there twice in two different jars.

**Comment by kaitoy** [comment]
I will fix it soon.
