### ISSUE TITLE
Add build procedure for IntelliJ IDEA

### ISSUE THREAD

**Issue by hsluoyz** [kaitoy/pcap4j#90]
As [this report](https://zeroturnaround.com/rebellabs/java-tools-and-technologies-landscape-2016-trends/) said, IntelliJ IDEA has replaced Eclipse to become the No.1 Java IDE in 2016. And as a Javaer, I daily use IDEA now and didn't install Eclipse for years. So could we add some build support for IDEA? Thanks!

**Comment by kaitoy** [comment]
I rather think it'd be better to support only command line build.
It's been a really long time since I last built Pcap4J on Eclipse...
I will remove it from the doc.

**Comment by kaitoy** [comment]
8b5c5643665b9abcc0af0cf40585a477ee52c99f
