### ISSUE TITLE
Error: Could not find or load main class org.pcap4j.sample.Docker

### ISSUE THREAD

**Issue by qfrank** [kaitoy/pcap4j#92]
execute docker run kaitoy/pcap4j:latest will get an error message 'Error: Could not find or load main class org.pcap4j.sample.Docker';

**resolution:** 
docker run -w /usr/local/src/pcap4j/build/docker_script kaitoy/pcap4j:latest

**Comment by kaitoy** [comment]
Thank you. I solved it.
