### ISSUE TITLE
Pointers to domain name in DNS packet wrap around at 63 (0x3F)

### ISSUE THREAD

**Issue by duyatran** [kaitoy/pcap4j#93]
Sorry if I'm missing some protocol but this is the first time I submit a issue report.

DNS records use pointers extensively for domain names. In DNS replies from a root server, I notice that some invalid domain names are created after calling decompress(headerRawData). The issue seems to be that pointers of these domain names (extracted from packets) wrap around after value 63. This seems to be confirmed by line 114 in DnsDomainName.java:

 `        foundPointer = (short) (ByteArrays.getShort(rawData, offset + cursor) & 0x3F);
`

0x3F only takes out 6 last bits of the short value, although [RFC-1035](https://www.ietf.org/rfc/rfc1035.txt), section 4.1.4 specifies 14 bits for the offset value. Maybe the mask should be 0x3FFF instead?

Thanks a lot!

**Comment by kaitoy** [comment]
Thank you for pointing it out.
It seems you're correct. I fixed it.
