### ISSUE TITLE
UdpPacket.hasValidChecksum seems to be broken for checksum 0xFFFF

### ISSUE THREAD

**Issue by michaelkoetter** [kaitoy/pcap4j#94]
If the UDP checksum is transferred as `0xFFFF`, `hasValidChecksum()` consistently returns false, whereas Wiresharks says the checksum is OK.
The attached file contains two such packets, whose payload seems to be intact (FIX/FAST encoded data) so it seems 0xFFFF would be the correct checksum indeed.
[udp-checksum-0xffff.zip](https://github.com/kaitoy/pcap4j/files/985015/udp-checksum-0xffff.zip)

**Comment by michaelkoetter** [comment]
Here's a test for the issue: a3460915813efd53cd88fffe4f62f53531f9b2bc

**Comment by michaelkoetter** [comment]
When I use `UdpPacket.Builder` to recalculate the checksum of the packet, it becomes `0x0000`.

According to RFC 768:
> If the computed  checksum  is zero,  it is transmitted  as all ones (the equivalent  in one's complement arithmetic).   An all zero  transmitted checksum  value means that the transmitter  generated  no checksum  (for debugging or for higher level protocols that don't care).

I can't figure out (yet) whether this needs to be done for all 'Internet Checksums' ie. in `ByteArrays.calcChecksum()` or just for the UDP checksum.

**Comment by kaitoy** [comment]
As far as I investigated, 0x0000 means +0 and 0xFFFF means -0, and both 0x0000 and 0xFFFF can be computed from the same byte array depending on calculation methods.
But 0x0000 means don't calculate checksum, so Pcap4J should use 0xFFFF if it gets 0x0000 as a result of its checksum calculation.
I will fix it soon.

**Comment by michaelkoetter** [comment]
I created a pull request against master which will be 2.0 by the looks of it, but can this also be added to the next 1.x release please? Thanks in advance 😄

**Comment by kaitoy** [comment]
I read RFC 1624 and I found no change is needed for the return value of calcChecksum.
hasValidChecksum should be changed instead. So I changed the fix.
Anyway, thank you for your contribution.
I merged the fix to the branch v1. It will be released after solving #99.
